// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateInvitationOperation      OperationName = "CreateInvitation"
	DisconnectIntegrationOperation OperationName = "DisconnectIntegration"
	GetIntegrationStatusOperation  OperationName = "GetIntegrationStatus"
	GetMeOperation                 OperationName = "GetMe"
	GetPendingOrgsOperation        OperationName = "GetPendingOrgs"
	ListGithubWebhooksOperation    OperationName = "ListGithubWebhooks"
	ListInvitationsOperation       OperationName = "ListInvitations"
	ListLinearWebhooksOperation    OperationName = "ListLinearWebhooks"
	ListMembersOperation           OperationName = "ListMembers"
	PingOperation                  OperationName = "Ping"
	SelectOrgOperation             OperationName = "SelectOrg"
	VerifyEmailOperation           OperationName = "VerifyEmail"
)
