// Code generated by ogen, DO NOT EDIT.

package api

// A generic error response.
// Ref: #/components/schemas/Error
type Error struct {
	// A human-readable description of the error.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) getMeRes()       {}
func (*Error) pingRes()        {}
func (*Error) verifyEmailRes() {}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// The response returned by the ping endpoint.
// Ref: #/components/schemas/PongResponse
type PongResponse struct {
	// Always the literal string "pong".
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *PongResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *PongResponse) SetMessage(val string) {
	s.Message = val
}

func (*PongResponse) pingRes() {}

// The authenticated WorkOS user.
// Ref: #/components/schemas/UserResponse
type UserResponse struct {
	// The WorkOS user ID.
	ID string `json:"id"`
	// The user's email address.
	Email string `json:"email"`
	// The user's first name, if set.
	FirstName OptString `json:"firstName"`
	// The user's last name, if set.
	LastName OptString `json:"lastName"`
}

// GetID returns the value of ID.
func (s *UserResponse) GetID() string {
	return s.ID
}

// GetEmail returns the value of Email.
func (s *UserResponse) GetEmail() string {
	return s.Email
}

// GetFirstName returns the value of FirstName.
func (s *UserResponse) GetFirstName() OptString {
	return s.FirstName
}

// GetLastName returns the value of LastName.
func (s *UserResponse) GetLastName() OptString {
	return s.LastName
}

// SetID sets the value of ID.
func (s *UserResponse) SetID(val string) {
	s.ID = val
}

// SetEmail sets the value of Email.
func (s *UserResponse) SetEmail(val string) {
	s.Email = val
}

// SetFirstName sets the value of FirstName.
func (s *UserResponse) SetFirstName(val OptString) {
	s.FirstName = val
}

// SetLastName sets the value of LastName.
func (s *UserResponse) SetLastName(val OptString) {
	s.LastName = val
}

func (*UserResponse) getMeRes()       {}
func (*UserResponse) verifyEmailRes() {}

// The verification code the user received by email.
// Ref: #/components/schemas/VerifyEmailRequest
type VerifyEmailRequest struct {
	// The one-time verification code WorkOS emailed to the user.
	Code string `json:"code"`
}

// GetCode returns the value of Code.
func (s *VerifyEmailRequest) GetCode() string {
	return s.Code
}

// SetCode sets the value of Code.
func (s *VerifyEmailRequest) SetCode(val string) {
	s.Code = val
}
