// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateInvitation implements createInvitation operation.
	//
	// Sends a WorkOS invitation for the given email to the caller's active organization (optionally with a
	// role). WorkOS emails the invitee a link; accepting it (by logging in with the invitation token)
	// creates their membership.
	//
	// POST /invitations
	CreateInvitation(ctx context.Context, req *CreateInvitationRequest) (CreateInvitationRes, error)
	// DisconnectIntegration implements disconnectIntegration operation.
	//
	// Removes the stored installation/token for the given provider at the given level. level=workspace
	// (default) removes the org-wide connection; level=user removes only the caller's own per-user
	// connection.
	//
	// POST /integrations/{provider}/disconnect
	DisconnectIntegration(ctx context.Context, params DisconnectIntegrationParams) (DisconnectIntegrationRes, error)
	// GetIntegrationStatus implements getIntegrationStatus operation.
	//
	// Returns the connection state of each supported integration (GitHub, Slack, Linear) for the caller's
	// active organization. Drives the integrations settings view. The actual connect/callback flows are
	// browser redirects (GET /integrations/{provider}/connect) and are not part of this JSON spec.
	//
	// GET /integrations/status
	GetIntegrationStatus(ctx context.Context) (GetIntegrationStatusRes, error)
	// GetLinearSettings implements getLinearSettings operation.
	//
	// Returns the org's Linear → Slack channel-creation rules (creation mode, trigger status, name
	// template, condition, auto-add bots), whether Linear is connected at the workspace level, and the
	// built-in sample events for the test panel.
	//
	// GET /integrations/linear/settings
	GetLinearSettings(ctx context.Context) (GetLinearSettingsRes, error)
	// GetMe implements getMe operation.
	//
	// Returns the WorkOS user backing the current session. Requires a valid `wos_session` cookie; returns
	// 401 when unauthenticated. The SPA calls this on load to decide whether to show the signed-in or
	// signed-out UI.
	//
	// GET /me
	GetMe(ctx context.Context) (GetMeRes, error)
	// GetPendingOrgs implements getPendingOrgs operation.
	//
	// During the org-selection step the SPA calls this to read the organizations the user may choose
	// between. The choices were stashed by `/auth/callback` in a short-lived sealed cookie. Returns 401 if
	// there is no pending selection.
	//
	// GET /auth/pending-orgs
	GetPendingOrgs(ctx context.Context) (GetPendingOrgsRes, error)
	// ListGithubWebhooks implements listGithubWebhooks operation.
	//
	// Returns the GitHub webhook events we have received and stored for the caller's active organization,
	// newest first. Events are stored when GitHub delivers them to POST /integrations/github/webhook (a
	// browser-external redirect-style route, not part of this JSON spec).
	//
	// GET /integrations/github/webhooks
	ListGithubWebhooks(ctx context.Context) (ListGithubWebhooksRes, error)
	// ListInvitations implements listInvitations operation.
	//
	// Returns the invitations for the caller's active organization. Requires a session scoped to an
	// organization.
	//
	// GET /invitations
	ListInvitations(ctx context.Context) (ListInvitationsRes, error)
	// ListLinearWebhooks implements listLinearWebhooks operation.
	//
	// Returns the Linear webhook events we have received and stored for the caller's active organization,
	// newest first. Events are stored when Linear delivers them to POST /integrations/linear/webhook (a
	// browser-external redirect-style route, not part of this JSON spec).
	//
	// GET /integrations/linear/webhooks
	ListLinearWebhooks(ctx context.Context) (ListLinearWebhooksRes, error)
	// ListMembers implements listMembers operation.
	//
	// Returns the active members of the caller's active organization, resolved from WorkOS organization
	// memberships. Requires a session scoped to an organization.
	//
	// GET /members
	ListMembers(ctx context.Context) (ListMembersRes, error)
	// Ping implements ping operation.
	//
	// Returns a pong message. Requires an authenticated session — the request must carry a valid
	// `wos_session` cookie. Used to verify the end-to-end authenticated transport.
	//
	// GET /ping
	Ping(ctx context.Context) (PingRes, error)
	// SaveLinearSettings implements saveLinearSettings operation.
	//
	// Persists the org's Linear settings. The name template and condition are validated (parsed) before
	// saving; a malformed template returns 400.
	//
	// PUT /integrations/linear/settings
	SaveLinearSettings(ctx context.Context, req *LinearSettings) (SaveLinearSettingsRes, error)
	// SelectOrg implements selectOrg operation.
	//
	// Finishes a login that WorkOS gated on organization selection. Exchanges the chosen organization plus
	// the stashed pending token for a session, sets the session cookie, and returns the user.
	//
	// POST /auth/select-org
	SelectOrg(ctx context.Context, req *SelectOrgRequest) (SelectOrgRes, error)
	// TestLinearTemplate implements testLinearTemplate operation.
	//
	// Renders nameTemplate and evaluates condition against the supplied event. Provide either a sampleId
	// (one of the built-in sample events) or a raw event JSON string. Returns the rendered name, the
	// condition result, and any template error (template errors are returned in-body, not as 4xx, so the
	// UI can show them inline).
	//
	// POST /integrations/linear/settings/test
	TestLinearTemplate(ctx context.Context, req *TemplateTestRequest) (TestLinearTemplateRes, error)
	// VerifyEmail implements verifyEmail operation.
	//
	// Some providers (notably GitHub OAuth) return an unverified email on first login, so WorkOS requires
	// email verification before issuing a session. The `/auth/callback` handler detects this, stores the
	// WorkOS `pending_authentication_token` in a short-lived sealed cookie, and sends the browser to the
	// SPA's verification step. The SPA collects the code WorkOS emailed and POSTs it here to finish
	// authentication and establish the session.
	//
	// POST /auth/verify-email
	VerifyEmail(ctx context.Context, req *VerifyEmailRequest) (VerifyEmailRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
