// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetMe implements getMe operation.
	//
	// Returns the WorkOS user backing the current session. Requires a valid `wos_session` cookie; returns
	// 401 when unauthenticated. The SPA calls this on load to decide whether to show the signed-in or
	// signed-out UI.
	//
	// GET /me
	GetMe(ctx context.Context) (GetMeRes, error)
	// Ping implements ping operation.
	//
	// Returns a pong message. Requires an authenticated session — the request must carry a valid
	// `wos_session` cookie. Used to verify the end-to-end authenticated transport.
	//
	// GET /ping
	Ping(ctx context.Context) (PingRes, error)
	// VerifyEmail implements verifyEmail operation.
	//
	// Some providers (notably GitHub OAuth) return an unverified email on first login, so WorkOS requires
	// email verification before issuing a session. The `/auth/callback` handler detects this, stores the
	// WorkOS `pending_authentication_token` in a short-lived sealed cookie, and sends the browser to the
	// SPA's verification step. The SPA collects the code WorkOS emailed and POSTs it here to finish
	// authentication and establish the session.
	//
	// POST /auth/verify-email
	VerifyEmail(ctx context.Context, req *VerifyEmailRequest) (VerifyEmailRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
