// Code generated by ogen, DO NOT EDIT.
package api

type CreateInvitationRes interface {
	createInvitationRes()
}

type GetMeRes interface {
	getMeRes()
}

type GetPendingOrgsRes interface {
	getPendingOrgsRes()
}

type ListInvitationsRes interface {
	listInvitationsRes()
}

type PingRes interface {
	pingRes()
}

type SelectOrgRes interface {
	selectOrgRes()
}

type VerifyEmailRes interface {
	verifyEmailRes()
}
