// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateInvitationOperation      OperationName = "CreateInvitation"
	CreateLinearSettingsOperation  OperationName = "CreateLinearSettings"
	DeleteLinearSettingsOperation  OperationName = "DeleteLinearSettings"
	DisconnectIntegrationOperation OperationName = "DisconnectIntegration"
	GetIntegrationStatusOperation  OperationName = "GetIntegrationStatus"
	GetLinearSettingsOperation     OperationName = "GetLinearSettings"
	GetMeOperation                 OperationName = "GetMe"
	GetPendingOrgsOperation        OperationName = "GetPendingOrgs"
	ListGithubWebhooksOperation    OperationName = "ListGithubWebhooks"
	ListInvitationsOperation       OperationName = "ListInvitations"
	ListLinearWebhooksOperation    OperationName = "ListLinearWebhooks"
	ListMembersOperation           OperationName = "ListMembers"
	PingOperation                  OperationName = "Ping"
	SelectOrgOperation             OperationName = "SelectOrg"
	SyncSettingsOperation          OperationName = "SyncSettings"
	TestLinearTemplateOperation    OperationName = "TestLinearTemplate"
	UpdateLinearSettingsOperation  OperationName = "UpdateLinearSettings"
	VerifyEmailOperation           OperationName = "VerifyEmail"
)
