// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
)

type CreateInvitationBadRequest Error

func (*CreateInvitationBadRequest) createInvitationRes() {}

// Invite an email address to the caller's active organization.
// Ref: #/components/schemas/CreateInvitationRequest
type CreateInvitationRequest struct {
	// The email address to invite.
	Email string `json:"email"`
	// Optional role slug to grant the invitee on acceptance.
	Role OptString `json:"role"`
}

// GetEmail returns the value of Email.
func (s *CreateInvitationRequest) GetEmail() string {
	return s.Email
}

// GetRole returns the value of Role.
func (s *CreateInvitationRequest) GetRole() OptString {
	return s.Role
}

// SetEmail sets the value of Email.
func (s *CreateInvitationRequest) SetEmail(val string) {
	s.Email = val
}

// SetRole sets the value of Role.
func (s *CreateInvitationRequest) SetRole(val OptString) {
	s.Role = val
}

type CreateInvitationUnauthorized Error

func (*CreateInvitationUnauthorized) createInvitationRes() {}

type DisconnectIntegrationProvider string

const (
	DisconnectIntegrationProviderGithub DisconnectIntegrationProvider = "github"
	DisconnectIntegrationProviderSlack  DisconnectIntegrationProvider = "slack"
)

// AllValues returns all DisconnectIntegrationProvider values.
func (DisconnectIntegrationProvider) AllValues() []DisconnectIntegrationProvider {
	return []DisconnectIntegrationProvider{
		DisconnectIntegrationProviderGithub,
		DisconnectIntegrationProviderSlack,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s DisconnectIntegrationProvider) MarshalText() ([]byte, error) {
	switch s {
	case DisconnectIntegrationProviderGithub:
		return []byte(s), nil
	case DisconnectIntegrationProviderSlack:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *DisconnectIntegrationProvider) UnmarshalText(data []byte) error {
	switch DisconnectIntegrationProvider(data) {
	case DisconnectIntegrationProviderGithub:
		*s = DisconnectIntegrationProviderGithub
		return nil
	case DisconnectIntegrationProviderSlack:
		*s = DisconnectIntegrationProviderSlack
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// A generic error response.
// Ref: #/components/schemas/Error
type Error struct {
	// A human-readable description of the error.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) disconnectIntegrationRes() {}
func (*Error) getIntegrationStatusRes()  {}
func (*Error) getMeRes()                 {}
func (*Error) getPendingOrgsRes()        {}
func (*Error) listInvitationsRes()       {}
func (*Error) pingRes()                  {}
func (*Error) selectOrgRes()             {}
func (*Error) verifyEmailRes()           {}

// The connection state of a single integration provider.
// Ref: #/components/schemas/IntegrationStatus
type IntegrationStatus struct {
	// The provider key.
	Provider string `json:"provider"`
	// Whether this provider is connected for the active organization.
	Connected bool `json:"connected"`
	// The connected account/workspace label (GitHub login, Slack team).
	Account OptString `json:"account"`
	// The WorkOS user id who connected it, if known.
	ConnectedBy OptString `json:"connectedBy"`
}

// GetProvider returns the value of Provider.
func (s *IntegrationStatus) GetProvider() string {
	return s.Provider
}

// GetConnected returns the value of Connected.
func (s *IntegrationStatus) GetConnected() bool {
	return s.Connected
}

// GetAccount returns the value of Account.
func (s *IntegrationStatus) GetAccount() OptString {
	return s.Account
}

// GetConnectedBy returns the value of ConnectedBy.
func (s *IntegrationStatus) GetConnectedBy() OptString {
	return s.ConnectedBy
}

// SetProvider sets the value of Provider.
func (s *IntegrationStatus) SetProvider(val string) {
	s.Provider = val
}

// SetConnected sets the value of Connected.
func (s *IntegrationStatus) SetConnected(val bool) {
	s.Connected = val
}

// SetAccount sets the value of Account.
func (s *IntegrationStatus) SetAccount(val OptString) {
	s.Account = val
}

// SetConnectedBy sets the value of ConnectedBy.
func (s *IntegrationStatus) SetConnectedBy(val OptString) {
	s.ConnectedBy = val
}

// Connection status for every supported integration.
// Ref: #/components/schemas/IntegrationStatusResponse
type IntegrationStatusResponse struct {
	Integrations []IntegrationStatus `json:"integrations"`
	// Whether the integration service is configured (database available) on the server.
	Configured bool `json:"configured"`
}

// GetIntegrations returns the value of Integrations.
func (s *IntegrationStatusResponse) GetIntegrations() []IntegrationStatus {
	return s.Integrations
}

// GetConfigured returns the value of Configured.
func (s *IntegrationStatusResponse) GetConfigured() bool {
	return s.Configured
}

// SetIntegrations sets the value of Integrations.
func (s *IntegrationStatusResponse) SetIntegrations(val []IntegrationStatus) {
	s.Integrations = val
}

// SetConfigured sets the value of Configured.
func (s *IntegrationStatusResponse) SetConfigured(val bool) {
	s.Configured = val
}

func (*IntegrationStatusResponse) disconnectIntegrationRes() {}
func (*IntegrationStatusResponse) getIntegrationStatusRes()  {}

// A list of invitations for the active organization.
// Ref: #/components/schemas/InvitationListResponse
type InvitationListResponse struct {
	Invitations []InvitationResponse `json:"invitations"`
}

// GetInvitations returns the value of Invitations.
func (s *InvitationListResponse) GetInvitations() []InvitationResponse {
	return s.Invitations
}

// SetInvitations sets the value of Invitations.
func (s *InvitationListResponse) SetInvitations(val []InvitationResponse) {
	s.Invitations = val
}

func (*InvitationListResponse) listInvitationsRes() {}

// A WorkOS organization invitation.
// Ref: #/components/schemas/InvitationResponse
type InvitationResponse struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	// The invitation state (pending, accepted, expired, revoked).
	State string `json:"state"`
	// ISO 8601 expiry timestamp.
	ExpiresAt OptString `json:"expiresAt"`
}

// GetID returns the value of ID.
func (s *InvitationResponse) GetID() string {
	return s.ID
}

// GetEmail returns the value of Email.
func (s *InvitationResponse) GetEmail() string {
	return s.Email
}

// GetState returns the value of State.
func (s *InvitationResponse) GetState() string {
	return s.State
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *InvitationResponse) GetExpiresAt() OptString {
	return s.ExpiresAt
}

// SetID sets the value of ID.
func (s *InvitationResponse) SetID(val string) {
	s.ID = val
}

// SetEmail sets the value of Email.
func (s *InvitationResponse) SetEmail(val string) {
	s.Email = val
}

// SetState sets the value of State.
func (s *InvitationResponse) SetState(val string) {
	s.State = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *InvitationResponse) SetExpiresAt(val OptString) {
	s.ExpiresAt = val
}

func (*InvitationResponse) createInvitationRes() {}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// A WorkOS organization the user belongs to.
// Ref: #/components/schemas/Organization
type Organization struct {
	// The WorkOS organization ID.
	ID string `json:"id"`
	// The organization's display name.
	Name string `json:"name"`
	// The user's role in this organization, if known.
	Role OptString `json:"role"`
}

// GetID returns the value of ID.
func (s *Organization) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Organization) GetName() string {
	return s.Name
}

// GetRole returns the value of Role.
func (s *Organization) GetRole() OptString {
	return s.Role
}

// SetID sets the value of ID.
func (s *Organization) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Organization) SetName(val string) {
	s.Name = val
}

// SetRole sets the value of Role.
func (s *Organization) SetRole(val OptString) {
	s.Role = val
}

// The organizations a user may choose between during org selection.
// Ref: #/components/schemas/PendingOrganizations
type PendingOrganizations struct {
	Organizations []Organization `json:"organizations"`
}

// GetOrganizations returns the value of Organizations.
func (s *PendingOrganizations) GetOrganizations() []Organization {
	return s.Organizations
}

// SetOrganizations sets the value of Organizations.
func (s *PendingOrganizations) SetOrganizations(val []Organization) {
	s.Organizations = val
}

func (*PendingOrganizations) getPendingOrgsRes() {}

// The response returned by the ping endpoint.
// Ref: #/components/schemas/PongResponse
type PongResponse struct {
	// Always the literal string "pong".
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *PongResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *PongResponse) SetMessage(val string) {
	s.Message = val
}

func (*PongResponse) pingRes() {}

// The organization the user chose during the org-selection step.
// Ref: #/components/schemas/SelectOrgRequest
type SelectOrgRequest struct {
	// The ID of the organization to authenticate into.
	OrganizationId string `json:"organizationId"`
}

// GetOrganizationId returns the value of OrganizationId.
func (s *SelectOrgRequest) GetOrganizationId() string {
	return s.OrganizationId
}

// SetOrganizationId sets the value of OrganizationId.
func (s *SelectOrgRequest) SetOrganizationId(val string) {
	s.OrganizationId = val
}

// The authenticated WorkOS user and their active organization context.
// Ref: #/components/schemas/UserResponse
type UserResponse struct {
	// The WorkOS user ID.
	ID string `json:"id"`
	// The user's email address.
	Email string `json:"email"`
	// The user's first name, if set.
	FirstName OptString `json:"firstName"`
	// The user's last name, if set.
	LastName OptString `json:"lastName"`
	// The ID of the organization the current session is scoped to, if any.
	OrganizationId OptString `json:"organizationId"`
	// The user's role within the active organization, if any.
	Role OptString `json:"role"`
	// All organizations the user is a member of.
	Organizations []Organization `json:"organizations"`
}

// GetID returns the value of ID.
func (s *UserResponse) GetID() string {
	return s.ID
}

// GetEmail returns the value of Email.
func (s *UserResponse) GetEmail() string {
	return s.Email
}

// GetFirstName returns the value of FirstName.
func (s *UserResponse) GetFirstName() OptString {
	return s.FirstName
}

// GetLastName returns the value of LastName.
func (s *UserResponse) GetLastName() OptString {
	return s.LastName
}

// GetOrganizationId returns the value of OrganizationId.
func (s *UserResponse) GetOrganizationId() OptString {
	return s.OrganizationId
}

// GetRole returns the value of Role.
func (s *UserResponse) GetRole() OptString {
	return s.Role
}

// GetOrganizations returns the value of Organizations.
func (s *UserResponse) GetOrganizations() []Organization {
	return s.Organizations
}

// SetID sets the value of ID.
func (s *UserResponse) SetID(val string) {
	s.ID = val
}

// SetEmail sets the value of Email.
func (s *UserResponse) SetEmail(val string) {
	s.Email = val
}

// SetFirstName sets the value of FirstName.
func (s *UserResponse) SetFirstName(val OptString) {
	s.FirstName = val
}

// SetLastName sets the value of LastName.
func (s *UserResponse) SetLastName(val OptString) {
	s.LastName = val
}

// SetOrganizationId sets the value of OrganizationId.
func (s *UserResponse) SetOrganizationId(val OptString) {
	s.OrganizationId = val
}

// SetRole sets the value of Role.
func (s *UserResponse) SetRole(val OptString) {
	s.Role = val
}

// SetOrganizations sets the value of Organizations.
func (s *UserResponse) SetOrganizations(val []Organization) {
	s.Organizations = val
}

func (*UserResponse) getMeRes()       {}
func (*UserResponse) selectOrgRes()   {}
func (*UserResponse) verifyEmailRes() {}

// The verification code the user received by email.
// Ref: #/components/schemas/VerifyEmailRequest
type VerifyEmailRequest struct {
	// The one-time verification code WorkOS emailed to the user.
	Code string `json:"code"`
}

// GetCode returns the value of Code.
func (s *VerifyEmailRequest) GetCode() string {
	return s.Code
}

// SetCode sets the value of Code.
func (s *VerifyEmailRequest) SetCode(val string) {
	s.Code = val
}
