// Code generated by ogen, DO NOT EDIT.
package api

type CreateBillingCheckoutRes interface {
	createBillingCheckoutRes()
}

type CreateBillingPortalRes interface {
	createBillingPortalRes()
}

type CreateInvitationRes interface {
	createInvitationRes()
}

type CreateLinearSettingsRes interface {
	createLinearSettingsRes()
}

type DeleteLinearSettingsRes interface {
	deleteLinearSettingsRes()
}

type DisconnectIntegrationRes interface {
	disconnectIntegrationRes()
}

type GetBillingRes interface {
	getBillingRes()
}

type GetIntegrationStatusRes interface {
	getIntegrationStatusRes()
}

type GetLinearSettingsRes interface {
	getLinearSettingsRes()
}

type GetMeRes interface {
	getMeRes()
}

type GetPendingOrgsRes interface {
	getPendingOrgsRes()
}

type ListGithubWebhooksRes interface {
	listGithubWebhooksRes()
}

type ListInvitationsRes interface {
	listInvitationsRes()
}

type ListLinearWebhooksRes interface {
	listLinearWebhooksRes()
}

type ListMembersRes interface {
	listMembersRes()
}

type PingRes interface {
	pingRes()
}

type SelectOrgRes interface {
	selectOrgRes()
}

type SubmitOssApplicationRes interface {
	submitOssApplicationRes()
}

type SyncSettingsRes interface {
	syncSettingsRes()
}

type TestLinearTemplateRes interface {
	testLinearTemplateRes()
}

type UpdateLinearSettingsRes interface {
	updateLinearSettingsRes()
}

type VerifyEmailRes interface {
	verifyEmailRes()
}
