// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
)

// A Stripe-hosted page (Checkout or Billing Portal) to redirect to.
// Ref: #/components/schemas/BillingRedirectResponse
type BillingRedirectResponse struct {
	// The URL the browser should navigate to.
	URL string `json:"url"`
}

// GetURL returns the value of URL.
func (s *BillingRedirectResponse) GetURL() string {
	return s.URL
}

// SetURL sets the value of URL.
func (s *BillingRedirectResponse) SetURL(val string) {
	s.URL = val
}

func (*BillingRedirectResponse) createBillingCheckoutRes() {}
func (*BillingRedirectResponse) createBillingPortalRes()   {}

// The active organization's full billing status.
// Ref: #/components/schemas/BillingStatusResponse
type BillingStatusResponse struct {
	// The organization's plan.
	Plan BillingStatusResponsePlan `json:"plan"`
	// Whether features are locked (trial expired, no subscription).
	Locked bool `json:"locked"`
	// When the 21-day trial ends/ended.
	TrialEndsAt time.Time `json:"trialEndsAt"`
	// Whether a live (non-canceled) Stripe subscription exists.
	Subscribed bool `json:"subscribed"`
	// The raw Stripe subscription status, once subscribed.
	StripeStatus OptString `json:"stripeStatus"`
	// The seat quantity on the Stripe subscription, once subscribed.
	Seats OptInt `json:"seats"`
	// The Pro price in cents per member per month.
	PriceCentsPerSeat int `json:"priceCentsPerSeat"`
	// The open-source application state, if one was submitted.
	OssApplicationStatus OptBillingStatusResponseOssApplicationStatus `json:"ossApplicationStatus"`
}

// GetPlan returns the value of Plan.
func (s *BillingStatusResponse) GetPlan() BillingStatusResponsePlan {
	return s.Plan
}

// GetLocked returns the value of Locked.
func (s *BillingStatusResponse) GetLocked() bool {
	return s.Locked
}

// GetTrialEndsAt returns the value of TrialEndsAt.
func (s *BillingStatusResponse) GetTrialEndsAt() time.Time {
	return s.TrialEndsAt
}

// GetSubscribed returns the value of Subscribed.
func (s *BillingStatusResponse) GetSubscribed() bool {
	return s.Subscribed
}

// GetStripeStatus returns the value of StripeStatus.
func (s *BillingStatusResponse) GetStripeStatus() OptString {
	return s.StripeStatus
}

// GetSeats returns the value of Seats.
func (s *BillingStatusResponse) GetSeats() OptInt {
	return s.Seats
}

// GetPriceCentsPerSeat returns the value of PriceCentsPerSeat.
func (s *BillingStatusResponse) GetPriceCentsPerSeat() int {
	return s.PriceCentsPerSeat
}

// GetOssApplicationStatus returns the value of OssApplicationStatus.
func (s *BillingStatusResponse) GetOssApplicationStatus() OptBillingStatusResponseOssApplicationStatus {
	return s.OssApplicationStatus
}

// SetPlan sets the value of Plan.
func (s *BillingStatusResponse) SetPlan(val BillingStatusResponsePlan) {
	s.Plan = val
}

// SetLocked sets the value of Locked.
func (s *BillingStatusResponse) SetLocked(val bool) {
	s.Locked = val
}

// SetTrialEndsAt sets the value of TrialEndsAt.
func (s *BillingStatusResponse) SetTrialEndsAt(val time.Time) {
	s.TrialEndsAt = val
}

// SetSubscribed sets the value of Subscribed.
func (s *BillingStatusResponse) SetSubscribed(val bool) {
	s.Subscribed = val
}

// SetStripeStatus sets the value of StripeStatus.
func (s *BillingStatusResponse) SetStripeStatus(val OptString) {
	s.StripeStatus = val
}

// SetSeats sets the value of Seats.
func (s *BillingStatusResponse) SetSeats(val OptInt) {
	s.Seats = val
}

// SetPriceCentsPerSeat sets the value of PriceCentsPerSeat.
func (s *BillingStatusResponse) SetPriceCentsPerSeat(val int) {
	s.PriceCentsPerSeat = val
}

// SetOssApplicationStatus sets the value of OssApplicationStatus.
func (s *BillingStatusResponse) SetOssApplicationStatus(val OptBillingStatusResponseOssApplicationStatus) {
	s.OssApplicationStatus = val
}

func (*BillingStatusResponse) getBillingRes()           {}
func (*BillingStatusResponse) submitOssApplicationRes() {}

// The open-source application state, if one was submitted.
type BillingStatusResponseOssApplicationStatus string

const (
	BillingStatusResponseOssApplicationStatusPending  BillingStatusResponseOssApplicationStatus = "pending"
	BillingStatusResponseOssApplicationStatusApproved BillingStatusResponseOssApplicationStatus = "approved"
	BillingStatusResponseOssApplicationStatusRejected BillingStatusResponseOssApplicationStatus = "rejected"
)

// AllValues returns all BillingStatusResponseOssApplicationStatus values.
func (BillingStatusResponseOssApplicationStatus) AllValues() []BillingStatusResponseOssApplicationStatus {
	return []BillingStatusResponseOssApplicationStatus{
		BillingStatusResponseOssApplicationStatusPending,
		BillingStatusResponseOssApplicationStatusApproved,
		BillingStatusResponseOssApplicationStatusRejected,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s BillingStatusResponseOssApplicationStatus) MarshalText() ([]byte, error) {
	switch s {
	case BillingStatusResponseOssApplicationStatusPending:
		return []byte(s), nil
	case BillingStatusResponseOssApplicationStatusApproved:
		return []byte(s), nil
	case BillingStatusResponseOssApplicationStatusRejected:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *BillingStatusResponseOssApplicationStatus) UnmarshalText(data []byte) error {
	switch BillingStatusResponseOssApplicationStatus(data) {
	case BillingStatusResponseOssApplicationStatusPending:
		*s = BillingStatusResponseOssApplicationStatusPending
		return nil
	case BillingStatusResponseOssApplicationStatusApproved:
		*s = BillingStatusResponseOssApplicationStatusApproved
		return nil
	case BillingStatusResponseOssApplicationStatusRejected:
		*s = BillingStatusResponseOssApplicationStatusRejected
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// The organization's plan.
type BillingStatusResponsePlan string

const (
	BillingStatusResponsePlanTrial      BillingStatusResponsePlan = "trial"
	BillingStatusResponsePlanPro        BillingStatusResponsePlan = "pro"
	BillingStatusResponsePlanOssFree    BillingStatusResponsePlan = "oss_free"
	BillingStatusResponsePlanEnterprise BillingStatusResponsePlan = "enterprise"
)

// AllValues returns all BillingStatusResponsePlan values.
func (BillingStatusResponsePlan) AllValues() []BillingStatusResponsePlan {
	return []BillingStatusResponsePlan{
		BillingStatusResponsePlanTrial,
		BillingStatusResponsePlanPro,
		BillingStatusResponsePlanOssFree,
		BillingStatusResponsePlanEnterprise,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s BillingStatusResponsePlan) MarshalText() ([]byte, error) {
	switch s {
	case BillingStatusResponsePlanTrial:
		return []byte(s), nil
	case BillingStatusResponsePlanPro:
		return []byte(s), nil
	case BillingStatusResponsePlanOssFree:
		return []byte(s), nil
	case BillingStatusResponsePlanEnterprise:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *BillingStatusResponsePlan) UnmarshalText(data []byte) error {
	switch BillingStatusResponsePlan(data) {
	case BillingStatusResponsePlanTrial:
		*s = BillingStatusResponsePlanTrial
		return nil
	case BillingStatusResponsePlanPro:
		*s = BillingStatusResponsePlanPro
		return nil
	case BillingStatusResponsePlanOssFree:
		*s = BillingStatusResponsePlanOssFree
		return nil
	case BillingStatusResponsePlanEnterprise:
		*s = BillingStatusResponsePlanEnterprise
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// The active organization's billing state, embedded in /me so the SPA can show the trial banner / lock
// screen without an extra request.
// Ref: #/components/schemas/BillingSummary
type BillingSummary struct {
	// The organization's plan.
	Plan BillingSummaryPlan `json:"plan"`
	// Whether features are locked (trial expired, no subscription).
	Locked bool `json:"locked"`
	// When the 21-day trial ends/ended.
	TrialEndsAt time.Time `json:"trialEndsAt"`
}

// GetPlan returns the value of Plan.
func (s *BillingSummary) GetPlan() BillingSummaryPlan {
	return s.Plan
}

// GetLocked returns the value of Locked.
func (s *BillingSummary) GetLocked() bool {
	return s.Locked
}

// GetTrialEndsAt returns the value of TrialEndsAt.
func (s *BillingSummary) GetTrialEndsAt() time.Time {
	return s.TrialEndsAt
}

// SetPlan sets the value of Plan.
func (s *BillingSummary) SetPlan(val BillingSummaryPlan) {
	s.Plan = val
}

// SetLocked sets the value of Locked.
func (s *BillingSummary) SetLocked(val bool) {
	s.Locked = val
}

// SetTrialEndsAt sets the value of TrialEndsAt.
func (s *BillingSummary) SetTrialEndsAt(val time.Time) {
	s.TrialEndsAt = val
}

// The organization's plan.
type BillingSummaryPlan string

const (
	BillingSummaryPlanTrial      BillingSummaryPlan = "trial"
	BillingSummaryPlanPro        BillingSummaryPlan = "pro"
	BillingSummaryPlanOssFree    BillingSummaryPlan = "oss_free"
	BillingSummaryPlanEnterprise BillingSummaryPlan = "enterprise"
)

// AllValues returns all BillingSummaryPlan values.
func (BillingSummaryPlan) AllValues() []BillingSummaryPlan {
	return []BillingSummaryPlan{
		BillingSummaryPlanTrial,
		BillingSummaryPlanPro,
		BillingSummaryPlanOssFree,
		BillingSummaryPlanEnterprise,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s BillingSummaryPlan) MarshalText() ([]byte, error) {
	switch s {
	case BillingSummaryPlanTrial:
		return []byte(s), nil
	case BillingSummaryPlanPro:
		return []byte(s), nil
	case BillingSummaryPlanOssFree:
		return []byte(s), nil
	case BillingSummaryPlanEnterprise:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *BillingSummaryPlan) UnmarshalText(data []byte) error {
	switch BillingSummaryPlan(data) {
	case BillingSummaryPlanTrial:
		*s = BillingSummaryPlanTrial
		return nil
	case BillingSummaryPlanPro:
		*s = BillingSummaryPlanPro
		return nil
	case BillingSummaryPlanOssFree:
		*s = BillingSummaryPlanOssFree
		return nil
	case BillingSummaryPlanEnterprise:
		*s = BillingSummaryPlanEnterprise
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateBillingCheckoutBadRequest Error

func (*CreateBillingCheckoutBadRequest) createBillingCheckoutRes() {}

type CreateBillingCheckoutConflict Error

func (*CreateBillingCheckoutConflict) createBillingCheckoutRes() {}

type CreateBillingCheckoutForbidden Error

func (*CreateBillingCheckoutForbidden) createBillingCheckoutRes() {}

type CreateBillingCheckoutUnauthorized Error

func (*CreateBillingCheckoutUnauthorized) createBillingCheckoutRes() {}

type CreateBillingPortalBadRequest Error

func (*CreateBillingPortalBadRequest) createBillingPortalRes() {}

type CreateBillingPortalForbidden Error

func (*CreateBillingPortalForbidden) createBillingPortalRes() {}

type CreateBillingPortalUnauthorized Error

func (*CreateBillingPortalUnauthorized) createBillingPortalRes() {}

type CreateInvitationBadRequest Error

func (*CreateInvitationBadRequest) createInvitationRes() {}

type CreateInvitationPaymentRequired Error

func (*CreateInvitationPaymentRequired) createInvitationRes() {}

// Invite an email address to the caller's active organization.
// Ref: #/components/schemas/CreateInvitationRequest
type CreateInvitationRequest struct {
	// The email address to invite.
	Email string `json:"email"`
	// Optional role slug to grant the invitee on acceptance.
	Role OptRoleSlug `json:"role"`
}

// GetEmail returns the value of Email.
func (s *CreateInvitationRequest) GetEmail() string {
	return s.Email
}

// GetRole returns the value of Role.
func (s *CreateInvitationRequest) GetRole() OptRoleSlug {
	return s.Role
}

// SetEmail sets the value of Email.
func (s *CreateInvitationRequest) SetEmail(val string) {
	s.Email = val
}

// SetRole sets the value of Role.
func (s *CreateInvitationRequest) SetRole(val OptRoleSlug) {
	s.Role = val
}

type CreateInvitationUnauthorized Error

func (*CreateInvitationUnauthorized) createInvitationRes() {}

type CreateLinearSettingsBadRequest Error

func (*CreateLinearSettingsBadRequest) createLinearSettingsRes() {}

type CreateLinearSettingsPaymentRequired Error

func (*CreateLinearSettingsPaymentRequired) createLinearSettingsRes() {}

type CreateLinearSettingsUnauthorized Error

func (*CreateLinearSettingsUnauthorized) createLinearSettingsRes() {}

type DeleteLinearSettingsPaymentRequired Error

func (*DeleteLinearSettingsPaymentRequired) deleteLinearSettingsRes() {}

type DeleteLinearSettingsUnauthorized Error

func (*DeleteLinearSettingsUnauthorized) deleteLinearSettingsRes() {}

type DeleteOrganizationAvatarBadRequest Error

func (*DeleteOrganizationAvatarBadRequest) deleteOrganizationAvatarRes() {}

type DeleteOrganizationAvatarForbidden Error

func (*DeleteOrganizationAvatarForbidden) deleteOrganizationAvatarRes() {}

type DeleteOrganizationAvatarUnauthorized Error

func (*DeleteOrganizationAvatarUnauthorized) deleteOrganizationAvatarRes() {}

type DisconnectIntegrationLevel string

const (
	DisconnectIntegrationLevelWorkspace DisconnectIntegrationLevel = "workspace"
	DisconnectIntegrationLevelUser      DisconnectIntegrationLevel = "user"
)

// AllValues returns all DisconnectIntegrationLevel values.
func (DisconnectIntegrationLevel) AllValues() []DisconnectIntegrationLevel {
	return []DisconnectIntegrationLevel{
		DisconnectIntegrationLevelWorkspace,
		DisconnectIntegrationLevelUser,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s DisconnectIntegrationLevel) MarshalText() ([]byte, error) {
	switch s {
	case DisconnectIntegrationLevelWorkspace:
		return []byte(s), nil
	case DisconnectIntegrationLevelUser:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *DisconnectIntegrationLevel) UnmarshalText(data []byte) error {
	switch DisconnectIntegrationLevel(data) {
	case DisconnectIntegrationLevelWorkspace:
		*s = DisconnectIntegrationLevelWorkspace
		return nil
	case DisconnectIntegrationLevelUser:
		*s = DisconnectIntegrationLevelUser
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type DisconnectIntegrationProvider string

const (
	DisconnectIntegrationProviderGithub DisconnectIntegrationProvider = "github"
	DisconnectIntegrationProviderSlack  DisconnectIntegrationProvider = "slack"
	DisconnectIntegrationProviderLinear DisconnectIntegrationProvider = "linear"
)

// AllValues returns all DisconnectIntegrationProvider values.
func (DisconnectIntegrationProvider) AllValues() []DisconnectIntegrationProvider {
	return []DisconnectIntegrationProvider{
		DisconnectIntegrationProviderGithub,
		DisconnectIntegrationProviderSlack,
		DisconnectIntegrationProviderLinear,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s DisconnectIntegrationProvider) MarshalText() ([]byte, error) {
	switch s {
	case DisconnectIntegrationProviderGithub:
		return []byte(s), nil
	case DisconnectIntegrationProviderSlack:
		return []byte(s), nil
	case DisconnectIntegrationProviderLinear:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *DisconnectIntegrationProvider) UnmarshalText(data []byte) error {
	switch DisconnectIntegrationProvider(data) {
	case DisconnectIntegrationProviderGithub:
		*s = DisconnectIntegrationProviderGithub
		return nil
	case DisconnectIntegrationProviderSlack:
		*s = DisconnectIntegrationProviderSlack
		return nil
	case DisconnectIntegrationProviderLinear:
		*s = DisconnectIntegrationProviderLinear
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// A generic error response.
// Ref: #/components/schemas/Error
type Error struct {
	// A human-readable description of the error.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) disconnectIntegrationRes() {}
func (*Error) getIntegrationStatusRes()  {}
func (*Error) getLinearSettingsRes()     {}
func (*Error) getMeRes()                 {}
func (*Error) getPendingOrgsRes()        {}
func (*Error) listGithubWebhooksRes()    {}
func (*Error) listInvitationsRes()       {}
func (*Error) listLinearWebhooksRes()    {}
func (*Error) listMembersRes()           {}
func (*Error) pingRes()                  {}
func (*Error) selectOrgRes()             {}
func (*Error) verifyEmailRes()           {}

type GetBillingBadRequest Error

func (*GetBillingBadRequest) getBillingRes() {}

type GetBillingUnauthorized Error

func (*GetBillingUnauthorized) getBillingRes() {}

type GetOrganizationProfileBadRequest Error

func (*GetOrganizationProfileBadRequest) getOrganizationProfileRes() {}

type GetOrganizationProfileUnauthorized Error

func (*GetOrganizationProfileUnauthorized) getOrganizationProfileRes() {}

// The connection state of a single integration provider at one level.
// Ref: #/components/schemas/IntegrationStatus
type IntegrationStatus struct {
	// The provider key.
	Provider string `json:"provider"`
	// Whether this entry is the organization's workspace-wide connection or the caller's own per-user
	// connection.
	Level IntegrationStatusLevel `json:"level"`
	// Whether this provider is connected at this level.
	Connected bool `json:"connected"`
	// The connected account/workspace label (GitHub login, Slack team).
	Account OptString `json:"account"`
	// The WorkOS user id who connected it, if known.
	ConnectedBy OptString `json:"connectedBy"`
}

// GetProvider returns the value of Provider.
func (s *IntegrationStatus) GetProvider() string {
	return s.Provider
}

// GetLevel returns the value of Level.
func (s *IntegrationStatus) GetLevel() IntegrationStatusLevel {
	return s.Level
}

// GetConnected returns the value of Connected.
func (s *IntegrationStatus) GetConnected() bool {
	return s.Connected
}

// GetAccount returns the value of Account.
func (s *IntegrationStatus) GetAccount() OptString {
	return s.Account
}

// GetConnectedBy returns the value of ConnectedBy.
func (s *IntegrationStatus) GetConnectedBy() OptString {
	return s.ConnectedBy
}

// SetProvider sets the value of Provider.
func (s *IntegrationStatus) SetProvider(val string) {
	s.Provider = val
}

// SetLevel sets the value of Level.
func (s *IntegrationStatus) SetLevel(val IntegrationStatusLevel) {
	s.Level = val
}

// SetConnected sets the value of Connected.
func (s *IntegrationStatus) SetConnected(val bool) {
	s.Connected = val
}

// SetAccount sets the value of Account.
func (s *IntegrationStatus) SetAccount(val OptString) {
	s.Account = val
}

// SetConnectedBy sets the value of ConnectedBy.
func (s *IntegrationStatus) SetConnectedBy(val OptString) {
	s.ConnectedBy = val
}

// Whether this entry is the organization's workspace-wide connection or the caller's own per-user
// connection.
type IntegrationStatusLevel string

const (
	IntegrationStatusLevelWorkspace IntegrationStatusLevel = "workspace"
	IntegrationStatusLevelUser      IntegrationStatusLevel = "user"
)

// AllValues returns all IntegrationStatusLevel values.
func (IntegrationStatusLevel) AllValues() []IntegrationStatusLevel {
	return []IntegrationStatusLevel{
		IntegrationStatusLevelWorkspace,
		IntegrationStatusLevelUser,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s IntegrationStatusLevel) MarshalText() ([]byte, error) {
	switch s {
	case IntegrationStatusLevelWorkspace:
		return []byte(s), nil
	case IntegrationStatusLevelUser:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *IntegrationStatusLevel) UnmarshalText(data []byte) error {
	switch IntegrationStatusLevel(data) {
	case IntegrationStatusLevelWorkspace:
		*s = IntegrationStatusLevelWorkspace
		return nil
	case IntegrationStatusLevelUser:
		*s = IntegrationStatusLevelUser
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Connection status for every supported integration.
// Ref: #/components/schemas/IntegrationStatusResponse
type IntegrationStatusResponse struct {
	Integrations []IntegrationStatus `json:"integrations"`
	// Whether the integration service is configured (database available) on the server.
	Configured bool `json:"configured"`
}

// GetIntegrations returns the value of Integrations.
func (s *IntegrationStatusResponse) GetIntegrations() []IntegrationStatus {
	return s.Integrations
}

// GetConfigured returns the value of Configured.
func (s *IntegrationStatusResponse) GetConfigured() bool {
	return s.Configured
}

// SetIntegrations sets the value of Integrations.
func (s *IntegrationStatusResponse) SetIntegrations(val []IntegrationStatus) {
	s.Integrations = val
}

// SetConfigured sets the value of Configured.
func (s *IntegrationStatusResponse) SetConfigured(val bool) {
	s.Configured = val
}

func (*IntegrationStatusResponse) disconnectIntegrationRes() {}
func (*IntegrationStatusResponse) getIntegrationStatusRes()  {}

// A list of invitations for the active organization.
// Ref: #/components/schemas/InvitationListResponse
type InvitationListResponse struct {
	Invitations []InvitationResponse `json:"invitations"`
}

// GetInvitations returns the value of Invitations.
func (s *InvitationListResponse) GetInvitations() []InvitationResponse {
	return s.Invitations
}

// SetInvitations sets the value of Invitations.
func (s *InvitationListResponse) SetInvitations(val []InvitationResponse) {
	s.Invitations = val
}

func (*InvitationListResponse) listInvitationsRes() {}

// A WorkOS organization invitation.
// Ref: #/components/schemas/InvitationResponse
type InvitationResponse struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	// The invitation state (pending, accepted, expired, revoked).
	State string `json:"state"`
	// ISO 8601 expiry timestamp.
	ExpiresAt OptString `json:"expiresAt"`
	// The role slug the invitee will be granted on acceptance, if any.
	Role OptString `json:"role"`
}

// GetID returns the value of ID.
func (s *InvitationResponse) GetID() string {
	return s.ID
}

// GetEmail returns the value of Email.
func (s *InvitationResponse) GetEmail() string {
	return s.Email
}

// GetState returns the value of State.
func (s *InvitationResponse) GetState() string {
	return s.State
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *InvitationResponse) GetExpiresAt() OptString {
	return s.ExpiresAt
}

// GetRole returns the value of Role.
func (s *InvitationResponse) GetRole() OptString {
	return s.Role
}

// SetID sets the value of ID.
func (s *InvitationResponse) SetID(val string) {
	s.ID = val
}

// SetEmail sets the value of Email.
func (s *InvitationResponse) SetEmail(val string) {
	s.Email = val
}

// SetState sets the value of State.
func (s *InvitationResponse) SetState(val string) {
	s.State = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *InvitationResponse) SetExpiresAt(val OptString) {
	s.ExpiresAt = val
}

// SetRole sets the value of Role.
func (s *InvitationResponse) SetRole(val OptString) {
	s.Role = val
}

func (*InvitationResponse) createInvitationRes() {}
func (*InvitationResponse) revokeInvitationRes() {}

// A Linear → Slack channel-creation config scoped to a single Linear team (teamId). The team is the
// config's identity; a team has at most one config.
// Ref: #/components/schemas/LinearSettings
type LinearSettings struct {
	// Stable id of this config. Omitted/empty when creating; returned on read and required in the URL for
	// update/delete.
	SettingId OptString `json:"settingId"`
	// 'status' auto-creates a channel when an issue reaches triggerStatus; 'condition' auto-creates when
	// conditionExpr evaluates true; 'manual' only creates via @notifbuddy.
	CreationMode LinearSettingsCreationMode `json:"creationMode"`
	// Linear workflow state name that triggers creation (status mode).
	TriggerStatus OptString `json:"triggerStatus"`
	// GitHub-Actions-expression template for the channel name.
	NameTemplate OptString `json:"nameTemplate"`
	// GitHub-Actions-expression that must be true for creation.
	ConditionExpr OptString `json:"conditionExpr"`
	// Slack member ids (U…) — bots and people — to auto-add on channel creation.
	AutoAddMembers []string `json:"autoAddMembers"`
	// The Linear team this config applies to.
	TeamId string `json:"teamId"`
}

// GetSettingId returns the value of SettingId.
func (s *LinearSettings) GetSettingId() OptString {
	return s.SettingId
}

// GetCreationMode returns the value of CreationMode.
func (s *LinearSettings) GetCreationMode() LinearSettingsCreationMode {
	return s.CreationMode
}

// GetTriggerStatus returns the value of TriggerStatus.
func (s *LinearSettings) GetTriggerStatus() OptString {
	return s.TriggerStatus
}

// GetNameTemplate returns the value of NameTemplate.
func (s *LinearSettings) GetNameTemplate() OptString {
	return s.NameTemplate
}

// GetConditionExpr returns the value of ConditionExpr.
func (s *LinearSettings) GetConditionExpr() OptString {
	return s.ConditionExpr
}

// GetAutoAddMembers returns the value of AutoAddMembers.
func (s *LinearSettings) GetAutoAddMembers() []string {
	return s.AutoAddMembers
}

// GetTeamId returns the value of TeamId.
func (s *LinearSettings) GetTeamId() string {
	return s.TeamId
}

// SetSettingId sets the value of SettingId.
func (s *LinearSettings) SetSettingId(val OptString) {
	s.SettingId = val
}

// SetCreationMode sets the value of CreationMode.
func (s *LinearSettings) SetCreationMode(val LinearSettingsCreationMode) {
	s.CreationMode = val
}

// SetTriggerStatus sets the value of TriggerStatus.
func (s *LinearSettings) SetTriggerStatus(val OptString) {
	s.TriggerStatus = val
}

// SetNameTemplate sets the value of NameTemplate.
func (s *LinearSettings) SetNameTemplate(val OptString) {
	s.NameTemplate = val
}

// SetConditionExpr sets the value of ConditionExpr.
func (s *LinearSettings) SetConditionExpr(val OptString) {
	s.ConditionExpr = val
}

// SetAutoAddMembers sets the value of AutoAddMembers.
func (s *LinearSettings) SetAutoAddMembers(val []string) {
	s.AutoAddMembers = val
}

// SetTeamId sets the value of TeamId.
func (s *LinearSettings) SetTeamId(val string) {
	s.TeamId = val
}

// 'status' auto-creates a channel when an issue reaches triggerStatus; 'condition' auto-creates when
// conditionExpr evaluates true; 'manual' only creates via @notifbuddy.
type LinearSettingsCreationMode string

const (
	LinearSettingsCreationModeStatus    LinearSettingsCreationMode = "status"
	LinearSettingsCreationModeManual    LinearSettingsCreationMode = "manual"
	LinearSettingsCreationModeCondition LinearSettingsCreationMode = "condition"
)

// AllValues returns all LinearSettingsCreationMode values.
func (LinearSettingsCreationMode) AllValues() []LinearSettingsCreationMode {
	return []LinearSettingsCreationMode{
		LinearSettingsCreationModeStatus,
		LinearSettingsCreationModeManual,
		LinearSettingsCreationModeCondition,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s LinearSettingsCreationMode) MarshalText() ([]byte, error) {
	switch s {
	case LinearSettingsCreationModeStatus:
		return []byte(s), nil
	case LinearSettingsCreationModeManual:
		return []byte(s), nil
	case LinearSettingsCreationModeCondition:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *LinearSettingsCreationMode) UnmarshalText(data []byte) error {
	switch LinearSettingsCreationMode(data) {
	case LinearSettingsCreationModeStatus:
		*s = LinearSettingsCreationModeStatus
		return nil
	case LinearSettingsCreationModeManual:
		*s = LinearSettingsCreationModeManual
		return nil
	case LinearSettingsCreationModeCondition:
		*s = LinearSettingsCreationModeCondition
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// All of an org's Linear configs plus context for the settings UI.
// Ref: #/components/schemas/LinearSettingsResponse
type LinearSettingsResponse struct {
	// Whether Linear is connected at the workspace level.
	Connected bool `json:"connected"`
	// The org's named channel-creation configs.
	Configs []LinearSettings `json:"configs"`
	// Synced Linear teams and their workflow states, for the "applies to" team picker and the
	// trigger-status dropdown.
	Teams []LinearTeamState `json:"teams"`
	// Synced Slack workspace members (bots + humans), for the auto-add bot/member pickers.
	SlackMembers []SlackMember `json:"slackMembers"`
	SampleEvents []SampleEvent `json:"sampleEvents"`
}

// GetConnected returns the value of Connected.
func (s *LinearSettingsResponse) GetConnected() bool {
	return s.Connected
}

// GetConfigs returns the value of Configs.
func (s *LinearSettingsResponse) GetConfigs() []LinearSettings {
	return s.Configs
}

// GetTeams returns the value of Teams.
func (s *LinearSettingsResponse) GetTeams() []LinearTeamState {
	return s.Teams
}

// GetSlackMembers returns the value of SlackMembers.
func (s *LinearSettingsResponse) GetSlackMembers() []SlackMember {
	return s.SlackMembers
}

// GetSampleEvents returns the value of SampleEvents.
func (s *LinearSettingsResponse) GetSampleEvents() []SampleEvent {
	return s.SampleEvents
}

// SetConnected sets the value of Connected.
func (s *LinearSettingsResponse) SetConnected(val bool) {
	s.Connected = val
}

// SetConfigs sets the value of Configs.
func (s *LinearSettingsResponse) SetConfigs(val []LinearSettings) {
	s.Configs = val
}

// SetTeams sets the value of Teams.
func (s *LinearSettingsResponse) SetTeams(val []LinearTeamState) {
	s.Teams = val
}

// SetSlackMembers sets the value of SlackMembers.
func (s *LinearSettingsResponse) SetSlackMembers(val []SlackMember) {
	s.SlackMembers = val
}

// SetSampleEvents sets the value of SampleEvents.
func (s *LinearSettingsResponse) SetSampleEvents(val []SampleEvent) {
	s.SampleEvents = val
}

func (*LinearSettingsResponse) createLinearSettingsRes() {}
func (*LinearSettingsResponse) deleteLinearSettingsRes() {}
func (*LinearSettingsResponse) getLinearSettingsRes()    {}
func (*LinearSettingsResponse) syncSettingsRes()         {}
func (*LinearSettingsResponse) updateLinearSettingsRes() {}

// A Linear team plus its synced workflow states.
// Ref: #/components/schemas/LinearTeamState
type LinearTeamState struct {
	TeamId   string                `json:"teamId"`
	TeamKey  OptString             `json:"teamKey"`
	TeamName string                `json:"teamName"`
	States   []LinearWorkflowState `json:"states"`
}

// GetTeamId returns the value of TeamId.
func (s *LinearTeamState) GetTeamId() string {
	return s.TeamId
}

// GetTeamKey returns the value of TeamKey.
func (s *LinearTeamState) GetTeamKey() OptString {
	return s.TeamKey
}

// GetTeamName returns the value of TeamName.
func (s *LinearTeamState) GetTeamName() string {
	return s.TeamName
}

// GetStates returns the value of States.
func (s *LinearTeamState) GetStates() []LinearWorkflowState {
	return s.States
}

// SetTeamId sets the value of TeamId.
func (s *LinearTeamState) SetTeamId(val string) {
	s.TeamId = val
}

// SetTeamKey sets the value of TeamKey.
func (s *LinearTeamState) SetTeamKey(val OptString) {
	s.TeamKey = val
}

// SetTeamName sets the value of TeamName.
func (s *LinearTeamState) SetTeamName(val string) {
	s.TeamName = val
}

// SetStates sets the value of States.
func (s *LinearTeamState) SetStates(val []LinearWorkflowState) {
	s.States = val
}

// One workflow state (issue status) of a Linear team.
// Ref: #/components/schemas/LinearWorkflowState
type LinearWorkflowState struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	// Linear's state category (e.g. backlog, unstarted, started, completed, canceled).
	Type  string    `json:"type"`
	Color OptString `json:"color"`
}

// GetID returns the value of ID.
func (s *LinearWorkflowState) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *LinearWorkflowState) GetName() string {
	return s.Name
}

// GetType returns the value of Type.
func (s *LinearWorkflowState) GetType() string {
	return s.Type
}

// GetColor returns the value of Color.
func (s *LinearWorkflowState) GetColor() OptString {
	return s.Color
}

// SetID sets the value of ID.
func (s *LinearWorkflowState) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *LinearWorkflowState) SetName(val string) {
	s.Name = val
}

// SetType sets the value of Type.
func (s *LinearWorkflowState) SetType(val string) {
	s.Type = val
}

// SetColor sets the value of Color.
func (s *LinearWorkflowState) SetColor(val OptString) {
	s.Color = val
}

// A list of members for the active organization.
// Ref: #/components/schemas/MemberListResponse
type MemberListResponse struct {
	Members []MemberResponse `json:"members"`
}

// GetMembers returns the value of Members.
func (s *MemberListResponse) GetMembers() []MemberResponse {
	return s.Members
}

// SetMembers sets the value of Members.
func (s *MemberListResponse) SetMembers(val []MemberResponse) {
	s.Members = val
}

func (*MemberListResponse) listMembersRes() {}

// A member of the active organization (a WorkOS organization membership).
// Ref: #/components/schemas/MemberResponse
type MemberResponse struct {
	// The WorkOS organization membership ID.
	ID string `json:"id"`
	// The WorkOS user ID of the member.
	UserId string `json:"userId"`
	// The member's email address.
	Email string `json:"email"`
	// The member's first name, if set.
	FirstName OptString `json:"firstName"`
	// The member's last name, if set.
	LastName OptString `json:"lastName"`
	// The member's role slug within the organization, if any.
	Role OptString `json:"role"`
	// URL of the member's profile picture, if any. For GitHub logins this is the user's GitHub avatar,
	// captured by WorkOS at sign-in.
	ProfilePictureUrl OptString `json:"profilePictureUrl"`
}

// GetID returns the value of ID.
func (s *MemberResponse) GetID() string {
	return s.ID
}

// GetUserId returns the value of UserId.
func (s *MemberResponse) GetUserId() string {
	return s.UserId
}

// GetEmail returns the value of Email.
func (s *MemberResponse) GetEmail() string {
	return s.Email
}

// GetFirstName returns the value of FirstName.
func (s *MemberResponse) GetFirstName() OptString {
	return s.FirstName
}

// GetLastName returns the value of LastName.
func (s *MemberResponse) GetLastName() OptString {
	return s.LastName
}

// GetRole returns the value of Role.
func (s *MemberResponse) GetRole() OptString {
	return s.Role
}

// GetProfilePictureUrl returns the value of ProfilePictureUrl.
func (s *MemberResponse) GetProfilePictureUrl() OptString {
	return s.ProfilePictureUrl
}

// SetID sets the value of ID.
func (s *MemberResponse) SetID(val string) {
	s.ID = val
}

// SetUserId sets the value of UserId.
func (s *MemberResponse) SetUserId(val string) {
	s.UserId = val
}

// SetEmail sets the value of Email.
func (s *MemberResponse) SetEmail(val string) {
	s.Email = val
}

// SetFirstName sets the value of FirstName.
func (s *MemberResponse) SetFirstName(val OptString) {
	s.FirstName = val
}

// SetLastName sets the value of LastName.
func (s *MemberResponse) SetLastName(val OptString) {
	s.LastName = val
}

// SetRole sets the value of Role.
func (s *MemberResponse) SetRole(val OptString) {
	s.Role = val
}

// SetProfilePictureUrl sets the value of ProfilePictureUrl.
func (s *MemberResponse) SetProfilePictureUrl(val OptString) {
	s.ProfilePictureUrl = val
}

func (*MemberResponse) updateMemberRoleRes() {}

// NewOptBillingStatusResponseOssApplicationStatus returns new OptBillingStatusResponseOssApplicationStatus with value set to v.
func NewOptBillingStatusResponseOssApplicationStatus(v BillingStatusResponseOssApplicationStatus) OptBillingStatusResponseOssApplicationStatus {
	return OptBillingStatusResponseOssApplicationStatus{
		Value: v,
		Set:   true,
	}
}

// OptBillingStatusResponseOssApplicationStatus is optional BillingStatusResponseOssApplicationStatus.
type OptBillingStatusResponseOssApplicationStatus struct {
	Value BillingStatusResponseOssApplicationStatus
	Set   bool
}

// IsSet returns true if OptBillingStatusResponseOssApplicationStatus was set.
func (o OptBillingStatusResponseOssApplicationStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBillingStatusResponseOssApplicationStatus) Reset() {
	var v BillingStatusResponseOssApplicationStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBillingStatusResponseOssApplicationStatus) SetTo(v BillingStatusResponseOssApplicationStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBillingStatusResponseOssApplicationStatus) Get() (v BillingStatusResponseOssApplicationStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBillingStatusResponseOssApplicationStatus) Or(d BillingStatusResponseOssApplicationStatus) BillingStatusResponseOssApplicationStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBillingSummary returns new OptBillingSummary with value set to v.
func NewOptBillingSummary(v BillingSummary) OptBillingSummary {
	return OptBillingSummary{
		Value: v,
		Set:   true,
	}
}

// OptBillingSummary is optional BillingSummary.
type OptBillingSummary struct {
	Value BillingSummary
	Set   bool
}

// IsSet returns true if OptBillingSummary was set.
func (o OptBillingSummary) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBillingSummary) Reset() {
	var v BillingSummary
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBillingSummary) SetTo(v BillingSummary) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBillingSummary) Get() (v BillingSummary, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBillingSummary) Or(d BillingSummary) BillingSummary {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDisconnectIntegrationLevel returns new OptDisconnectIntegrationLevel with value set to v.
func NewOptDisconnectIntegrationLevel(v DisconnectIntegrationLevel) OptDisconnectIntegrationLevel {
	return OptDisconnectIntegrationLevel{
		Value: v,
		Set:   true,
	}
}

// OptDisconnectIntegrationLevel is optional DisconnectIntegrationLevel.
type OptDisconnectIntegrationLevel struct {
	Value DisconnectIntegrationLevel
	Set   bool
}

// IsSet returns true if OptDisconnectIntegrationLevel was set.
func (o OptDisconnectIntegrationLevel) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDisconnectIntegrationLevel) Reset() {
	var v DisconnectIntegrationLevel
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDisconnectIntegrationLevel) SetTo(v DisconnectIntegrationLevel) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDisconnectIntegrationLevel) Get() (v DisconnectIntegrationLevel, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDisconnectIntegrationLevel) Or(d DisconnectIntegrationLevel) DisconnectIntegrationLevel {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRoleSlug returns new OptRoleSlug with value set to v.
func NewOptRoleSlug(v RoleSlug) OptRoleSlug {
	return OptRoleSlug{
		Value: v,
		Set:   true,
	}
}

// OptRoleSlug is optional RoleSlug.
type OptRoleSlug struct {
	Value RoleSlug
	Set   bool
}

// IsSet returns true if OptRoleSlug was set.
func (o OptRoleSlug) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRoleSlug) Reset() {
	var v RoleSlug
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRoleSlug) SetTo(v RoleSlug) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRoleSlug) Get() (v RoleSlug, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRoleSlug) Or(d RoleSlug) RoleSlug {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// The active organization's editable profile.
// Ref: #/components/schemas/OrgProfileResponse
type OrgProfileResponse struct {
	// The WorkOS organization ID.
	ID string `json:"id"`
	// The organization's display name.
	Name string `json:"name"`
	// Seed for the client-rendered generated avatar.
	AvatarSeed string `json:"avatarSeed"`
	// Data URL of the uploaded avatar image. Absent when no image has been uploaded; render the generated
	// avatar from avatarSeed instead.
	AvatarUrl OptString `json:"avatarUrl"`
}

// GetID returns the value of ID.
func (s *OrgProfileResponse) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *OrgProfileResponse) GetName() string {
	return s.Name
}

// GetAvatarSeed returns the value of AvatarSeed.
func (s *OrgProfileResponse) GetAvatarSeed() string {
	return s.AvatarSeed
}

// GetAvatarUrl returns the value of AvatarUrl.
func (s *OrgProfileResponse) GetAvatarUrl() OptString {
	return s.AvatarUrl
}

// SetID sets the value of ID.
func (s *OrgProfileResponse) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *OrgProfileResponse) SetName(val string) {
	s.Name = val
}

// SetAvatarSeed sets the value of AvatarSeed.
func (s *OrgProfileResponse) SetAvatarSeed(val string) {
	s.AvatarSeed = val
}

// SetAvatarUrl sets the value of AvatarUrl.
func (s *OrgProfileResponse) SetAvatarUrl(val OptString) {
	s.AvatarUrl = val
}

func (*OrgProfileResponse) deleteOrganizationAvatarRes()     {}
func (*OrgProfileResponse) getOrganizationProfileRes()       {}
func (*OrgProfileResponse) regenerateOrganizationAvatarRes() {}
func (*OrgProfileResponse) updateOrganizationProfileRes()    {}
func (*OrgProfileResponse) uploadOrganizationAvatarRes()     {}

// A WorkOS organization the user belongs to.
// Ref: #/components/schemas/Organization
type Organization struct {
	// The WorkOS organization ID.
	ID string `json:"id"`
	// The organization's display name.
	Name string `json:"name"`
	// The user's role in this organization, if known.
	Role OptString `json:"role"`
}

// GetID returns the value of ID.
func (s *Organization) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Organization) GetName() string {
	return s.Name
}

// GetRole returns the value of Role.
func (s *Organization) GetRole() OptString {
	return s.Role
}

// SetID sets the value of ID.
func (s *Organization) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Organization) SetName(val string) {
	s.Name = val
}

// SetRole sets the value of Role.
func (s *Organization) SetRole(val OptString) {
	s.Role = val
}

// An application for the free open-source tier.
// Ref: #/components/schemas/OssApplicationRequest
type OssApplicationRequest struct {
	// Link to the open-source repo or sponsorship page.
	SponsorUrl string `json:"sponsorUrl"`
	// Optional context for the reviewer.
	Note OptString `json:"note"`
}

// GetSponsorUrl returns the value of SponsorUrl.
func (s *OssApplicationRequest) GetSponsorUrl() string {
	return s.SponsorUrl
}

// GetNote returns the value of Note.
func (s *OssApplicationRequest) GetNote() OptString {
	return s.Note
}

// SetSponsorUrl sets the value of SponsorUrl.
func (s *OssApplicationRequest) SetSponsorUrl(val string) {
	s.SponsorUrl = val
}

// SetNote sets the value of Note.
func (s *OssApplicationRequest) SetNote(val OptString) {
	s.Note = val
}

// The organizations a user may choose between during org selection.
// Ref: #/components/schemas/PendingOrganizations
type PendingOrganizations struct {
	Organizations []Organization `json:"organizations"`
}

// GetOrganizations returns the value of Organizations.
func (s *PendingOrganizations) GetOrganizations() []Organization {
	return s.Organizations
}

// SetOrganizations sets the value of Organizations.
func (s *PendingOrganizations) SetOrganizations(val []Organization) {
	s.Organizations = val
}

func (*PendingOrganizations) getPendingOrgsRes() {}

// The response returned by the ping endpoint.
// Ref: #/components/schemas/PongResponse
type PongResponse struct {
	// Always the literal string "pong".
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *PongResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *PongResponse) SetMessage(val string) {
	s.Message = val
}

func (*PongResponse) pingRes() {}

type RegenerateOrganizationAvatarBadRequest Error

func (*RegenerateOrganizationAvatarBadRequest) regenerateOrganizationAvatarRes() {}

type RegenerateOrganizationAvatarForbidden Error

func (*RegenerateOrganizationAvatarForbidden) regenerateOrganizationAvatarRes() {}

type RegenerateOrganizationAvatarUnauthorized Error

func (*RegenerateOrganizationAvatarUnauthorized) regenerateOrganizationAvatarRes() {}

type RevokeInvitationBadRequest Error

func (*RevokeInvitationBadRequest) revokeInvitationRes() {}

type RevokeInvitationNotFound Error

func (*RevokeInvitationNotFound) revokeInvitationRes() {}

type RevokeInvitationUnauthorized Error

func (*RevokeInvitationUnauthorized) revokeInvitationRes() {}

// An organization role slug.
// Ref: #/components/schemas/RoleSlug
type RoleSlug string

const (
	RoleSlugAdmin  RoleSlug = "admin"
	RoleSlugMember RoleSlug = "member"
	RoleSlugViewer RoleSlug = "viewer"
)

// AllValues returns all RoleSlug values.
func (RoleSlug) AllValues() []RoleSlug {
	return []RoleSlug{
		RoleSlugAdmin,
		RoleSlugMember,
		RoleSlugViewer,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RoleSlug) MarshalText() ([]byte, error) {
	switch s {
	case RoleSlugAdmin:
		return []byte(s), nil
	case RoleSlugMember:
		return []byte(s), nil
	case RoleSlugViewer:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RoleSlug) UnmarshalText(data []byte) error {
	switch RoleSlug(data) {
	case RoleSlugAdmin:
		*s = RoleSlugAdmin
		return nil
	case RoleSlugMember:
		*s = RoleSlugMember
		return nil
	case RoleSlugViewer:
		*s = RoleSlugViewer
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// A built-in example event for the settings test panel.
// Ref: #/components/schemas/SampleEvent
type SampleEvent struct {
	ID    string `json:"id"`
	Label string `json:"label"`
	// The event envelope JSON (as a string).
	Raw string `json:"raw"`
}

// GetID returns the value of ID.
func (s *SampleEvent) GetID() string {
	return s.ID
}

// GetLabel returns the value of Label.
func (s *SampleEvent) GetLabel() string {
	return s.Label
}

// GetRaw returns the value of Raw.
func (s *SampleEvent) GetRaw() string {
	return s.Raw
}

// SetID sets the value of ID.
func (s *SampleEvent) SetID(val string) {
	s.ID = val
}

// SetLabel sets the value of Label.
func (s *SampleEvent) SetLabel(val string) {
	s.Label = val
}

// SetRaw sets the value of Raw.
func (s *SampleEvent) SetRaw(val string) {
	s.Raw = val
}

// The organization the user chose during the org-selection step.
// Ref: #/components/schemas/SelectOrgRequest
type SelectOrgRequest struct {
	// The ID of the organization to authenticate into.
	OrganizationId string `json:"organizationId"`
}

// GetOrganizationId returns the value of OrganizationId.
func (s *SelectOrgRequest) GetOrganizationId() string {
	return s.OrganizationId
}

// SetOrganizationId sets the value of OrganizationId.
func (s *SelectOrgRequest) SetOrganizationId(val string) {
	s.OrganizationId = val
}

// A synced Slack workspace member (bot/app or human).
// Ref: #/components/schemas/SlackMember
type SlackMember struct {
	// Slack member id (U…); what conversations.invite needs.
	MemberId string `json:"memberId"`
	// Display/real name, falling back to the handle.
	Name    string    `json:"name"`
	IconUrl OptString `json:"iconUrl"`
	IsBot   bool      `json:"isBot"`
}

// GetMemberId returns the value of MemberId.
func (s *SlackMember) GetMemberId() string {
	return s.MemberId
}

// GetName returns the value of Name.
func (s *SlackMember) GetName() string {
	return s.Name
}

// GetIconUrl returns the value of IconUrl.
func (s *SlackMember) GetIconUrl() OptString {
	return s.IconUrl
}

// GetIsBot returns the value of IsBot.
func (s *SlackMember) GetIsBot() bool {
	return s.IsBot
}

// SetMemberId sets the value of MemberId.
func (s *SlackMember) SetMemberId(val string) {
	s.MemberId = val
}

// SetName sets the value of Name.
func (s *SlackMember) SetName(val string) {
	s.Name = val
}

// SetIconUrl sets the value of IconUrl.
func (s *SlackMember) SetIconUrl(val OptString) {
	s.IconUrl = val
}

// SetIsBot sets the value of IsBot.
func (s *SlackMember) SetIsBot(val bool) {
	s.IsBot = val
}

type SubmitOssApplicationBadRequest Error

func (*SubmitOssApplicationBadRequest) submitOssApplicationRes() {}

type SubmitOssApplicationConflict Error

func (*SubmitOssApplicationConflict) submitOssApplicationRes() {}

type SubmitOssApplicationForbidden Error

func (*SubmitOssApplicationForbidden) submitOssApplicationRes() {}

type SubmitOssApplicationUnauthorized Error

func (*SubmitOssApplicationUnauthorized) submitOssApplicationRes() {}

type SyncSettingsPaymentRequired Error

func (*SyncSettingsPaymentRequired) syncSettingsRes() {}

type SyncSettingsUnauthorized Error

func (*SyncSettingsUnauthorized) syncSettingsRes() {}

// A template-test request. Provide exactly one event source: sampleId (a built-in sample event) or
// event (a raw envelope JSON string).
// Ref: #/components/schemas/TemplateTestRequest
type TemplateTestRequest struct {
	NameTemplate OptString `json:"nameTemplate"`
	Condition    OptString `json:"condition"`
	// Id of a built-in sample event.
	SampleId OptString `json:"sampleId"`
	// A raw event envelope JSON string (alternative to sampleId).
	Event OptString `json:"event"`
}

// GetNameTemplate returns the value of NameTemplate.
func (s *TemplateTestRequest) GetNameTemplate() OptString {
	return s.NameTemplate
}

// GetCondition returns the value of Condition.
func (s *TemplateTestRequest) GetCondition() OptString {
	return s.Condition
}

// GetSampleId returns the value of SampleId.
func (s *TemplateTestRequest) GetSampleId() OptString {
	return s.SampleId
}

// GetEvent returns the value of Event.
func (s *TemplateTestRequest) GetEvent() OptString {
	return s.Event
}

// SetNameTemplate sets the value of NameTemplate.
func (s *TemplateTestRequest) SetNameTemplate(val OptString) {
	s.NameTemplate = val
}

// SetCondition sets the value of Condition.
func (s *TemplateTestRequest) SetCondition(val OptString) {
	s.Condition = val
}

// SetSampleId sets the value of SampleId.
func (s *TemplateTestRequest) SetSampleId(val OptString) {
	s.SampleId = val
}

// SetEvent sets the value of Event.
func (s *TemplateTestRequest) SetEvent(val OptString) {
	s.Event = val
}

// Result of rendering a template + evaluating a condition.
// Ref: #/components/schemas/TemplateTestResponse
type TemplateTestResponse struct {
	// The rendered channel name (empty if no template / on error).
	Name string `json:"name"`
	// Whether the condition evaluated true.
	ConditionResult bool `json:"conditionResult"`
	// A template/condition error, if any (shown inline by the UI).
	Error OptString `json:"error"`
}

// GetName returns the value of Name.
func (s *TemplateTestResponse) GetName() string {
	return s.Name
}

// GetConditionResult returns the value of ConditionResult.
func (s *TemplateTestResponse) GetConditionResult() bool {
	return s.ConditionResult
}

// GetError returns the value of Error.
func (s *TemplateTestResponse) GetError() OptString {
	return s.Error
}

// SetName sets the value of Name.
func (s *TemplateTestResponse) SetName(val string) {
	s.Name = val
}

// SetConditionResult sets the value of ConditionResult.
func (s *TemplateTestResponse) SetConditionResult(val bool) {
	s.ConditionResult = val
}

// SetError sets the value of Error.
func (s *TemplateTestResponse) SetError(val OptString) {
	s.Error = val
}

func (*TemplateTestResponse) testLinearTemplateRes() {}

type TestLinearTemplateBadRequest Error

func (*TestLinearTemplateBadRequest) testLinearTemplateRes() {}

type TestLinearTemplatePaymentRequired Error

func (*TestLinearTemplatePaymentRequired) testLinearTemplateRes() {}

type TestLinearTemplateUnauthorized Error

func (*TestLinearTemplateUnauthorized) testLinearTemplateRes() {}

type UpdateLinearSettingsBadRequest Error

func (*UpdateLinearSettingsBadRequest) updateLinearSettingsRes() {}

type UpdateLinearSettingsNotFound Error

func (*UpdateLinearSettingsNotFound) updateLinearSettingsRes() {}

type UpdateLinearSettingsPaymentRequired Error

func (*UpdateLinearSettingsPaymentRequired) updateLinearSettingsRes() {}

type UpdateLinearSettingsUnauthorized Error

func (*UpdateLinearSettingsUnauthorized) updateLinearSettingsRes() {}

type UpdateMemberRoleBadRequest Error

func (*UpdateMemberRoleBadRequest) updateMemberRoleRes() {}

type UpdateMemberRoleForbidden Error

func (*UpdateMemberRoleForbidden) updateMemberRoleRes() {}

type UpdateMemberRoleNotFound Error

func (*UpdateMemberRoleNotFound) updateMemberRoleRes() {}

// Change an organization member's role.
// Ref: #/components/schemas/UpdateMemberRoleRequest
type UpdateMemberRoleRequest struct {
	// The role slug to assign to the member.
	Role RoleSlug `json:"role"`
}

// GetRole returns the value of Role.
func (s *UpdateMemberRoleRequest) GetRole() RoleSlug {
	return s.Role
}

// SetRole sets the value of Role.
func (s *UpdateMemberRoleRequest) SetRole(val RoleSlug) {
	s.Role = val
}

type UpdateMemberRoleUnauthorized Error

func (*UpdateMemberRoleUnauthorized) updateMemberRoleRes() {}

// Rename the active organization.
// Ref: #/components/schemas/UpdateOrgProfileRequest
type UpdateOrgProfileRequest struct {
	// The new organization name.
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *UpdateOrgProfileRequest) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *UpdateOrgProfileRequest) SetName(val string) {
	s.Name = val
}

type UpdateOrganizationProfileBadRequest Error

func (*UpdateOrganizationProfileBadRequest) updateOrganizationProfileRes() {}

type UpdateOrganizationProfileForbidden Error

func (*UpdateOrganizationProfileForbidden) updateOrganizationProfileRes() {}

type UpdateOrganizationProfileUnauthorized Error

func (*UpdateOrganizationProfileUnauthorized) updateOrganizationProfileRes() {}

// An uploaded avatar image, as a data URL.
// Ref: #/components/schemas/UploadOrgAvatarRequest
type UploadOrgAvatarRequest struct {
	// Data:image/png;base64,... (PNG, JPEG, or WebP; at most 512 KiB decoded).
	ImageDataUrl string `json:"imageDataUrl"`
}

// GetImageDataUrl returns the value of ImageDataUrl.
func (s *UploadOrgAvatarRequest) GetImageDataUrl() string {
	return s.ImageDataUrl
}

// SetImageDataUrl sets the value of ImageDataUrl.
func (s *UploadOrgAvatarRequest) SetImageDataUrl(val string) {
	s.ImageDataUrl = val
}

type UploadOrganizationAvatarBadRequest Error

func (*UploadOrganizationAvatarBadRequest) uploadOrganizationAvatarRes() {}

type UploadOrganizationAvatarForbidden Error

func (*UploadOrganizationAvatarForbidden) uploadOrganizationAvatarRes() {}

type UploadOrganizationAvatarUnauthorized Error

func (*UploadOrganizationAvatarUnauthorized) uploadOrganizationAvatarRes() {}

// The authenticated WorkOS user and their active organization context.
// Ref: #/components/schemas/UserResponse
type UserResponse struct {
	// The WorkOS user ID.
	ID string `json:"id"`
	// The user's email address.
	Email string `json:"email"`
	// The user's first name, if set.
	FirstName OptString `json:"firstName"`
	// The user's last name, if set.
	LastName OptString `json:"lastName"`
	// URL of the user's profile picture, if any. For GitHub logins this is the user's GitHub avatar,
	// captured by WorkOS at sign-in.
	ProfilePictureUrl OptString `json:"profilePictureUrl"`
	// The ID of the organization the current session is scoped to, if any.
	OrganizationId OptString `json:"organizationId"`
	// The user's role within the active organization, if any.
	Role OptString `json:"role"`
	// All organizations the user is a member of.
	Organizations []Organization    `json:"organizations"`
	Billing       OptBillingSummary `json:"billing"`
}

// GetID returns the value of ID.
func (s *UserResponse) GetID() string {
	return s.ID
}

// GetEmail returns the value of Email.
func (s *UserResponse) GetEmail() string {
	return s.Email
}

// GetFirstName returns the value of FirstName.
func (s *UserResponse) GetFirstName() OptString {
	return s.FirstName
}

// GetLastName returns the value of LastName.
func (s *UserResponse) GetLastName() OptString {
	return s.LastName
}

// GetProfilePictureUrl returns the value of ProfilePictureUrl.
func (s *UserResponse) GetProfilePictureUrl() OptString {
	return s.ProfilePictureUrl
}

// GetOrganizationId returns the value of OrganizationId.
func (s *UserResponse) GetOrganizationId() OptString {
	return s.OrganizationId
}

// GetRole returns the value of Role.
func (s *UserResponse) GetRole() OptString {
	return s.Role
}

// GetOrganizations returns the value of Organizations.
func (s *UserResponse) GetOrganizations() []Organization {
	return s.Organizations
}

// GetBilling returns the value of Billing.
func (s *UserResponse) GetBilling() OptBillingSummary {
	return s.Billing
}

// SetID sets the value of ID.
func (s *UserResponse) SetID(val string) {
	s.ID = val
}

// SetEmail sets the value of Email.
func (s *UserResponse) SetEmail(val string) {
	s.Email = val
}

// SetFirstName sets the value of FirstName.
func (s *UserResponse) SetFirstName(val OptString) {
	s.FirstName = val
}

// SetLastName sets the value of LastName.
func (s *UserResponse) SetLastName(val OptString) {
	s.LastName = val
}

// SetProfilePictureUrl sets the value of ProfilePictureUrl.
func (s *UserResponse) SetProfilePictureUrl(val OptString) {
	s.ProfilePictureUrl = val
}

// SetOrganizationId sets the value of OrganizationId.
func (s *UserResponse) SetOrganizationId(val OptString) {
	s.OrganizationId = val
}

// SetRole sets the value of Role.
func (s *UserResponse) SetRole(val OptString) {
	s.Role = val
}

// SetOrganizations sets the value of Organizations.
func (s *UserResponse) SetOrganizations(val []Organization) {
	s.Organizations = val
}

// SetBilling sets the value of Billing.
func (s *UserResponse) SetBilling(val OptBillingSummary) {
	s.Billing = val
}

func (*UserResponse) getMeRes()       {}
func (*UserResponse) selectOrgRes()   {}
func (*UserResponse) verifyEmailRes() {}

// The verification code the user received by email.
// Ref: #/components/schemas/VerifyEmailRequest
type VerifyEmailRequest struct {
	// The one-time verification code WorkOS emailed to the user.
	Code string `json:"code"`
}

// GetCode returns the value of Code.
func (s *VerifyEmailRequest) GetCode() string {
	return s.Code
}

// SetCode sets the value of Code.
func (s *VerifyEmailRequest) SetCode(val string) {
	s.Code = val
}

// A stored GitHub webhook delivery.
// Ref: #/components/schemas/WebhookEvent
type WebhookEvent struct {
	// The X-GitHub-Delivery id (unique per delivery).
	DeliveryId string `json:"deliveryId"`
	// The X-GitHub-Event type.
	EventType string `json:"eventType"`
	// The payload action, when present.
	Action OptString `json:"action"`
	// ISO 8601 timestamp when we received it.
	ReceivedAt string `json:"receivedAt"`
	// The raw webhook JSON payload (as a string).
	Payload OptString `json:"payload"`
}

// GetDeliveryId returns the value of DeliveryId.
func (s *WebhookEvent) GetDeliveryId() string {
	return s.DeliveryId
}

// GetEventType returns the value of EventType.
func (s *WebhookEvent) GetEventType() string {
	return s.EventType
}

// GetAction returns the value of Action.
func (s *WebhookEvent) GetAction() OptString {
	return s.Action
}

// GetReceivedAt returns the value of ReceivedAt.
func (s *WebhookEvent) GetReceivedAt() string {
	return s.ReceivedAt
}

// GetPayload returns the value of Payload.
func (s *WebhookEvent) GetPayload() OptString {
	return s.Payload
}

// SetDeliveryId sets the value of DeliveryId.
func (s *WebhookEvent) SetDeliveryId(val string) {
	s.DeliveryId = val
}

// SetEventType sets the value of EventType.
func (s *WebhookEvent) SetEventType(val string) {
	s.EventType = val
}

// SetAction sets the value of Action.
func (s *WebhookEvent) SetAction(val OptString) {
	s.Action = val
}

// SetReceivedAt sets the value of ReceivedAt.
func (s *WebhookEvent) SetReceivedAt(val string) {
	s.ReceivedAt = val
}

// SetPayload sets the value of Payload.
func (s *WebhookEvent) SetPayload(val OptString) {
	s.Payload = val
}

// Recent webhook events for the active organization.
// Ref: #/components/schemas/WebhookListResponse
type WebhookListResponse struct {
	Events []WebhookEvent `json:"events"`
}

// GetEvents returns the value of Events.
func (s *WebhookListResponse) GetEvents() []WebhookEvent {
	return s.Events
}

// SetEvents sets the value of Events.
func (s *WebhookListResponse) SetEvents(val []WebhookEvent) {
	s.Events = val
}

func (*WebhookListResponse) listGithubWebhooksRes() {}
func (*WebhookListResponse) listLinearWebhooksRes() {}
