// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn30AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn38AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn31AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn7AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn34AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn10AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn5AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn37AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn12AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn20AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn8AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [1]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "auth/"

				if l := len("auth/"); len(elem) >= l && elem[0:l] == "auth/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'p': // Prefix: "pending-orgs"

					if l := len("pending-orgs"); len(elem) >= l && elem[0:l] == "pending-orgs" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetPendingOrgsRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 's': // Prefix: "select-org"

					if l := len("select-org"); len(elem) >= l && elem[0:l] == "select-org" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleSelectOrgRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn30AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'v': // Prefix: "verify-email"

					if l := len("verify-email"); len(elem) >= l && elem[0:l] == "verify-email" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleVerifyEmailRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn38AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'b': // Prefix: "billing"

				if l := len("billing"); len(elem) >= l && elem[0:l] == "billing" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleGetBillingRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'c': // Prefix: "checkout"

						if l := len("checkout"); len(elem) >= l && elem[0:l] == "checkout" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleCreateBillingCheckoutRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'o': // Prefix: "oss-application"

						if l := len("oss-application"); len(elem) >= l && elem[0:l] == "oss-application" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleSubmitOssApplicationRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn31AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'p': // Prefix: "portal"

						if l := len("portal"); len(elem) >= l && elem[0:l] == "portal" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleCreateBillingPortalRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'i': // Prefix: "in"

				if l := len("in"); len(elem) >= l && elem[0:l] == "in" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 't': // Prefix: "tegrations/"

					if l := len("tegrations/"); len(elem) >= l && elem[0:l] == "tegrations/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'l': // Prefix: "linear/"
						origElem := elem
						if l := len("linear/"); len(elem) >= l && elem[0:l] == "linear/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 's': // Prefix: "settings"

							if l := len("settings"); len(elem) >= l && elem[0:l] == "settings" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleGetLinearSettingsRequest([0]string{}, elemIsEscaped, w, r)
								case "POST":
									s.handleCreateLinearSettingsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,POST",
										allowedHeaders: rn7AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 't': // Prefix: "test"
									origElem := elem
									if l := len("test"); len(elem) >= l && elem[0:l] == "test" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleTestLinearTemplateRequest([0]string{}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn34AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}

									elem = origElem
								}
								// Param: "settingId"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "DELETE":
										s.handleDeleteLinearSettingsRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									case "PUT":
										s.handleUpdateLinearSettingsRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "DELETE,PUT",
											allowedHeaders: rn10AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'w': // Prefix: "webhooks"

							if l := len("webhooks"); len(elem) >= l && elem[0:l] == "webhooks" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListLinearWebhooksRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

						elem = origElem
					case 's': // Prefix: "s"
						origElem := elem
						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'e': // Prefix: "ettings/sync"

							if l := len("ettings/sync"); len(elem) >= l && elem[0:l] == "ettings/sync" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleSyncSettingsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 't': // Prefix: "tatus"

							if l := len("tatus"); len(elem) >= l && elem[0:l] == "tatus" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetIntegrationStatusRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

						elem = origElem
					}
					// Param: "provider"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/disconnect"

						if l := len("/disconnect"); len(elem) >= l && elem[0:l] == "/disconnect" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleDisconnectIntegrationRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				case 'v': // Prefix: "vitations"

					if l := len("vitations"); len(elem) >= l && elem[0:l] == "vitations" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleListInvitationsRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handleCreateInvitationRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,POST",
								allowedHeaders: rn5AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "invitationId"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "DELETE":
								s.handleRevokeInvitationRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'm': // Prefix: "me"

				if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleGetMeRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case 'm': // Prefix: "mbers"

					if l := len("mbers"); len(elem) >= l && elem[0:l] == "mbers" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleListMembersRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "membershipId"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/role"

							if l := len("/role"); len(elem) >= l && elem[0:l] == "/role" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "PUT":
									s.handleUpdateMemberRoleRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "PUT",
										allowedHeaders: rn37AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			case 'o': // Prefix: "organization"

				if l := len("organization"); len(elem) >= l && elem[0:l] == "organization" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "avatar"

						if l := len("avatar"); len(elem) >= l && elem[0:l] == "avatar" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "DELETE":
								s.handleDeleteOrganizationAvatarRequest([0]string{}, elemIsEscaped, w, r)
							case "PUT":
								s.handleUploadOrganizationAvatarRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE,PUT",
									allowedHeaders: rn12AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/regenerate"

							if l := len("/regenerate"); len(elem) >= l && elem[0:l] == "/regenerate" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleRegenerateOrganizationAvatarRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					case 'p': // Prefix: "profile"

						if l := len("profile"); len(elem) >= l && elem[0:l] == "profile" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetOrganizationProfileRequest([0]string{}, elemIsEscaped, w, r)
							case "PUT":
								s.handleUpdateOrganizationProfileRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET,PUT",
									allowedHeaders: rn20AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				case 's': // Prefix: "s"

					if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleCreateOrganizationRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn8AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'p': // Prefix: "ping"

				if l := len("ping"); len(elem) >= l && elem[0:l] == "ping" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handlePingRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [1]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "auth/"

				if l := len("auth/"); len(elem) >= l && elem[0:l] == "auth/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'p': // Prefix: "pending-orgs"

					if l := len("pending-orgs"); len(elem) >= l && elem[0:l] == "pending-orgs" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = GetPendingOrgsOperation
							r.summary = "List organizations awaiting selection"
							r.operationID = "getPendingOrgs"
							r.operationGroup = ""
							r.pathPattern = "/auth/pending-orgs"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 's': // Prefix: "select-org"

					if l := len("select-org"); len(elem) >= l && elem[0:l] == "select-org" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = SelectOrgOperation
							r.summary = "Complete login by choosing an organization"
							r.operationID = "selectOrg"
							r.operationGroup = ""
							r.pathPattern = "/auth/select-org"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'v': // Prefix: "verify-email"

					if l := len("verify-email"); len(elem) >= l && elem[0:l] == "verify-email" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = VerifyEmailOperation
							r.summary = "Complete email-verification during login"
							r.operationID = "verifyEmail"
							r.operationGroup = ""
							r.pathPattern = "/auth/verify-email"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			case 'b': // Prefix: "billing"

				if l := len("billing"); len(elem) >= l && elem[0:l] == "billing" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = GetBillingOperation
						r.summary = "Billing status for the active organization"
						r.operationID = "getBilling"
						r.operationGroup = ""
						r.pathPattern = "/billing"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'c': // Prefix: "checkout"

						if l := len("checkout"); len(elem) >= l && elem[0:l] == "checkout" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = CreateBillingCheckoutOperation
								r.summary = "Start a Stripe Checkout session for the Pro plan"
								r.operationID = "createBillingCheckout"
								r.operationGroup = ""
								r.pathPattern = "/billing/checkout"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'o': // Prefix: "oss-application"

						if l := len("oss-application"); len(elem) >= l && elem[0:l] == "oss-application" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = SubmitOssApplicationOperation
								r.summary = "Apply for the free open-source tier"
								r.operationID = "submitOssApplication"
								r.operationGroup = ""
								r.pathPattern = "/billing/oss-application"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'p': // Prefix: "portal"

						if l := len("portal"); len(elem) >= l && elem[0:l] == "portal" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = CreateBillingPortalOperation
								r.summary = "Open the Stripe Customer Portal"
								r.operationID = "createBillingPortal"
								r.operationGroup = ""
								r.pathPattern = "/billing/portal"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'i': // Prefix: "in"

				if l := len("in"); len(elem) >= l && elem[0:l] == "in" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 't': // Prefix: "tegrations/"

					if l := len("tegrations/"); len(elem) >= l && elem[0:l] == "tegrations/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'l': // Prefix: "linear/"
						origElem := elem
						if l := len("linear/"); len(elem) >= l && elem[0:l] == "linear/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 's': // Prefix: "settings"

							if l := len("settings"); len(elem) >= l && elem[0:l] == "settings" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = GetLinearSettingsOperation
									r.summary = "Linear channel-creation configs for the active organization"
									r.operationID = "getLinearSettings"
									r.operationGroup = ""
									r.pathPattern = "/integrations/linear/settings"
									r.args = args
									r.count = 0
									return r, true
								case "POST":
									r.name = CreateLinearSettingsOperation
									r.summary = "Create a Linear channel-creation config"
									r.operationID = "createLinearSettings"
									r.operationGroup = ""
									r.pathPattern = "/integrations/linear/settings"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 't': // Prefix: "test"
									origElem := elem
									if l := len("test"); len(elem) >= l && elem[0:l] == "test" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = TestLinearTemplateOperation
											r.summary = "Test a name template + condition against a sample or pasted event"
											r.operationID = "testLinearTemplate"
											r.operationGroup = ""
											r.pathPattern = "/integrations/linear/settings/test"
											r.args = args
											r.count = 0
											return r, true
										default:
											return
										}
									}

									elem = origElem
								}
								// Param: "settingId"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "DELETE":
										r.name = DeleteLinearSettingsOperation
										r.summary = "Delete a Linear channel-creation config"
										r.operationID = "deleteLinearSettings"
										r.operationGroup = ""
										r.pathPattern = "/integrations/linear/settings/{settingId}"
										r.args = args
										r.count = 1
										return r, true
									case "PUT":
										r.name = UpdateLinearSettingsOperation
										r.summary = "Update a Linear channel-creation config"
										r.operationID = "updateLinearSettings"
										r.operationGroup = ""
										r.pathPattern = "/integrations/linear/settings/{settingId}"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						case 'w': // Prefix: "webhooks"

							if l := len("webhooks"); len(elem) >= l && elem[0:l] == "webhooks" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListLinearWebhooksOperation
									r.summary = "Recent Linear webhook deliveries for the active organization"
									r.operationID = "listLinearWebhooks"
									r.operationGroup = ""
									r.pathPattern = "/integrations/linear/webhooks"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

						elem = origElem
					case 's': // Prefix: "s"
						origElem := elem
						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'e': // Prefix: "ettings/sync"

							if l := len("ettings/sync"); len(elem) >= l && elem[0:l] == "ettings/sync" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = SyncSettingsOperation
									r.summary = "Re-sync Linear teams/statuses and Slack members"
									r.operationID = "syncSettings"
									r.operationGroup = ""
									r.pathPattern = "/integrations/settings/sync"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 't': // Prefix: "tatus"

							if l := len("tatus"); len(elem) >= l && elem[0:l] == "tatus" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetIntegrationStatusOperation
									r.summary = "Integration connection status for the active organization"
									r.operationID = "getIntegrationStatus"
									r.operationGroup = ""
									r.pathPattern = "/integrations/status"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

						elem = origElem
					}
					// Param: "provider"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/disconnect"

						if l := len("/disconnect"); len(elem) >= l && elem[0:l] == "/disconnect" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = DisconnectIntegrationOperation
								r.summary = "Disconnect an integration from the active organization"
								r.operationID = "disconnectIntegration"
								r.operationGroup = ""
								r.pathPattern = "/integrations/{provider}/disconnect"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				case 'v': // Prefix: "vitations"

					if l := len("vitations"); len(elem) >= l && elem[0:l] == "vitations" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = ListInvitationsOperation
							r.summary = "List the active organization's invitations"
							r.operationID = "listInvitations"
							r.operationGroup = ""
							r.pathPattern = "/invitations"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = CreateInvitationOperation
							r.summary = "Invite an email to the active organization"
							r.operationID = "createInvitation"
							r.operationGroup = ""
							r.pathPattern = "/invitations"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "invitationId"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "DELETE":
								r.name = RevokeInvitationOperation
								r.summary = "Revoke a pending invitation"
								r.operationID = "revokeInvitation"
								r.operationGroup = ""
								r.pathPattern = "/invitations/{invitationId}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'm': // Prefix: "me"

				if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = GetMeOperation
						r.summary = "Get the current user"
						r.operationID = "getMe"
						r.operationGroup = ""
						r.pathPattern = "/me"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case 'm': // Prefix: "mbers"

					if l := len("mbers"); len(elem) >= l && elem[0:l] == "mbers" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = ListMembersOperation
							r.summary = "List the active organization's members"
							r.operationID = "listMembers"
							r.operationGroup = ""
							r.pathPattern = "/members"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "membershipId"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/role"

							if l := len("/role"); len(elem) >= l && elem[0:l] == "/role" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "PUT":
									r.name = UpdateMemberRoleOperation
									r.summary = "Change a member's role in the active organization"
									r.operationID = "updateMemberRole"
									r.operationGroup = ""
									r.pathPattern = "/members/{membershipId}/role"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			case 'o': // Prefix: "organization"

				if l := len("organization"); len(elem) >= l && elem[0:l] == "organization" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "avatar"

						if l := len("avatar"); len(elem) >= l && elem[0:l] == "avatar" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "DELETE":
								r.name = DeleteOrganizationAvatarOperation
								r.summary = "Remove the uploaded avatar"
								r.operationID = "deleteOrganizationAvatar"
								r.operationGroup = ""
								r.pathPattern = "/organization/avatar"
								r.args = args
								r.count = 0
								return r, true
							case "PUT":
								r.name = UploadOrganizationAvatarOperation
								r.summary = "Upload the organization's avatar image"
								r.operationID = "uploadOrganizationAvatar"
								r.operationGroup = ""
								r.pathPattern = "/organization/avatar"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/regenerate"

							if l := len("/regenerate"); len(elem) >= l && elem[0:l] == "/regenerate" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = RegenerateOrganizationAvatarOperation
									r.summary = "Re-roll the generated avatar"
									r.operationID = "regenerateOrganizationAvatar"
									r.operationGroup = ""
									r.pathPattern = "/organization/avatar/regenerate"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					case 'p': // Prefix: "profile"

						if l := len("profile"); len(elem) >= l && elem[0:l] == "profile" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetOrganizationProfileOperation
								r.summary = "The active organization's profile"
								r.operationID = "getOrganizationProfile"
								r.operationGroup = ""
								r.pathPattern = "/organization/profile"
								r.args = args
								r.count = 0
								return r, true
							case "PUT":
								r.name = UpdateOrganizationProfileOperation
								r.summary = "Rename the active organization"
								r.operationID = "updateOrganizationProfile"
								r.operationGroup = ""
								r.pathPattern = "/organization/profile"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				case 's': // Prefix: "s"

					if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = CreateOrganizationOperation
							r.summary = "Create an organization and scope the session to it"
							r.operationID = "createOrganization"
							r.operationGroup = ""
							r.pathPattern = "/organizations"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			case 'p': // Prefix: "ping"

				if l := len("ping"); len(elem) >= l && elem[0:l] == "ping" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = PingOperation
						r.summary = "Ping the server"
						r.operationID = "ping"
						r.operationGroup = ""
						r.pathPattern = "/ping"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			}

		}
	}
	return r, false
}
