/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping the server
         * @description Returns a pong message. Requires an authenticated session — the request
         *     must carry a valid `wos_session` cookie. Used to verify the end-to-end
         *     authenticated transport.
         */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete email-verification during login
         * @description Some providers (notably GitHub OAuth) return an unverified email on first
         *     login, so WorkOS requires email verification before issuing a session. The
         *     `/auth/callback` handler detects this, stores the WorkOS
         *     `pending_authentication_token` in a short-lived sealed cookie, and sends
         *     the browser to the SPA's verification step. The SPA collects the code
         *     WorkOS emailed and POSTs it here to finish authentication and establish
         *     the session.
         */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current user
         * @description Returns the WorkOS user backing the current session. Requires a valid
         *     `wos_session` cookie; returns 401 when unauthenticated. The SPA calls this
         *     on load to decide whether to show the signed-in or signed-out UI.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/pending-orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organizations awaiting selection
         * @description During the org-selection step the SPA calls this to read the organizations
         *     the user may choose between. The choices were stashed by `/auth/callback`
         *     in a short-lived sealed cookie. Returns 401 if there is no pending
         *     selection.
         */
        get: operations["getPendingOrgs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/select-org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete login by choosing an organization
         * @description Finishes a login that WorkOS gated on organization selection. Exchanges
         *     the chosen organization plus the stashed pending token for a session,
         *     sets the session cookie, and returns the user.
         */
        post: operations["selectOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the active organization's invitations
         * @description Returns the invitations for the caller's active organization. Requires a
         *     session scoped to an organization.
         */
        get: operations["listInvitations"];
        put?: never;
        /**
         * Invite an email to the active organization
         * @description Sends a WorkOS invitation for the given email to the caller's active
         *     organization (optionally with a role). WorkOS emails the invitee a link;
         *     accepting it (by logging in with the invitation token) creates their
         *     membership.
         */
        post: operations["createInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Integration connection status for the active organization
         * @description Returns the connection state of each supported integration (GitHub,
         *     Slack) for the caller's active organization. Drives both the onboarding
         *     wizard and the integrations settings view. The actual connect/callback
         *     flows are browser redirects (GET /integrations/{provider}/connect) and
         *     are not part of this JSON spec.
         */
        get: operations["getIntegrationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/{provider}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disconnect an integration from the active organization
         * @description Removes the stored installation/token for the given provider.
         */
        post: operations["disconnectIntegration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The response returned by the ping endpoint. */
        PongResponse: {
            /**
             * @description Always the literal string "pong".
             * @example pong
             */
            message: string;
        };
        /** @description The authenticated WorkOS user and their active organization context. */
        UserResponse: {
            /**
             * @description The WorkOS user ID.
             * @example user_01H...
             */
            id: string;
            /**
             * @description The user's email address.
             * @example jane@example.com
             */
            email: string;
            /**
             * @description The user's first name, if set.
             * @example Jane
             */
            firstName?: string;
            /**
             * @description The user's last name, if set.
             * @example Doe
             */
            lastName?: string;
            /**
             * @description The ID of the organization the current session is scoped to, if any.
             * @example org_01H...
             */
            organizationId?: string;
            /**
             * @description The user's role within the active organization, if any.
             * @example admin
             */
            role?: string;
            /** @description All organizations the user is a member of. */
            organizations?: components["schemas"]["Organization"][];
        };
        /** @description A WorkOS organization the user belongs to. */
        Organization: {
            /**
             * @description The WorkOS organization ID.
             * @example org_01H...
             */
            id: string;
            /**
             * @description The organization's display name.
             * @example Acme Inc
             */
            name: string;
            /**
             * @description The user's role in this organization, if known.
             * @example member
             */
            role?: string;
        };
        /** @description The verification code the user received by email. */
        VerifyEmailRequest: {
            /**
             * @description The one-time verification code WorkOS emailed to the user.
             * @example 123456
             */
            code: string;
        };
        /** @description The organization the user chose during the org-selection step. */
        SelectOrgRequest: {
            /**
             * @description The ID of the organization to authenticate into.
             * @example org_01H...
             */
            organizationId: string;
        };
        /** @description The organizations a user may choose between during org selection. */
        PendingOrganizations: {
            organizations: components["schemas"]["Organization"][];
        };
        /** @description Invite an email address to the caller's active organization. */
        CreateInvitationRequest: {
            /**
             * @description The email address to invite.
             * @example newteammate@example.com
             */
            email: string;
            /**
             * @description Optional role slug to grant the invitee on acceptance.
             * @example member
             */
            role?: string;
        };
        /** @description A WorkOS organization invitation. */
        InvitationResponse: {
            /** @example invitation_01H... */
            id: string;
            /** @example newteammate@example.com */
            email: string;
            /**
             * @description The invitation state (pending, accepted, expired, revoked).
             * @example pending
             */
            state: string;
            /**
             * @description ISO 8601 expiry timestamp.
             * @example 2026-07-03T00:00:00Z
             */
            expiresAt?: string;
        };
        /** @description A list of invitations for the active organization. */
        InvitationListResponse: {
            invitations: components["schemas"]["InvitationResponse"][];
        };
        /** @description The connection state of a single integration provider. */
        IntegrationStatus: {
            /**
             * @description The provider key.
             * @example github
             */
            provider: string;
            /** @description Whether this provider is connected for the active organization. */
            connected: boolean;
            /**
             * @description The connected account/workspace label (GitHub login, Slack team).
             * @example acme
             */
            account?: string;
            /**
             * @description The WorkOS user id who connected it, if known.
             * @example user_01H...
             */
            connectedBy?: string;
        };
        /** @description Connection status for every supported integration. */
        IntegrationStatusResponse: {
            integrations: components["schemas"]["IntegrationStatus"][];
            /** @description Whether the integration service is configured (database available) on the server. */
            configured: boolean;
        };
        /** @description A generic error response. */
        Error: {
            /**
             * @description A human-readable description of the error.
             * @example unauthorized
             */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A pong response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PongResponse"];
                };
            };
            /** @description No valid session — the caller is not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Verification succeeded; the session cookie is now set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /**
             * @description No pending verification, an expired/invalid pending token, or a wrong
             *     verification code.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description No valid session — the caller is not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPendingOrgs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The organizations to choose from. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingOrganizations"];
                };
            };
            /** @description No pending organization selection. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    selectOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectOrgRequest"];
            };
        };
        responses: {
            /** @description Selection succeeded; the session cookie is now set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description No pending selection, or an invalid/expired pending token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The organization's invitations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationListResponse"];
                };
            };
            /** @description No valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationRequest"];
            };
        };
        responses: {
            /** @description The created invitation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"];
                };
            };
            /** @description The request was invalid (e.g. no active organization). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getIntegrationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-provider connection status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationStatusResponse"];
                };
            };
            /** @description No valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    disconnectIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "github" | "slack";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disconnected (or was already not connected). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationStatusResponse"];
                };
            };
            /** @description No valid session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
