// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// JoinWaitlist implements joinWaitlist operation.
	//
	// Public, unauthenticated. Stores an email address from the marketing landing page's waitlist form.
	// Idempotent — submitting an address that is already on the list succeeds again rather than
	// erroring, so the form never punishes a double-click or a returning visitor.
	//
	// POST /waitlist
	JoinWaitlist(ctx context.Context, req *WaitlistRequest) (JoinWaitlistRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
